### DISCUSSION TITLE
Creating duplicate releases

### DISCUSSION THREAD

**Discussion by evanchooly** [jreleaser/jreleaser#1004] [Q&A]
When I run a `full-release` on my snapshot build (because I push new snapshots on each commit), I end up with two different releases sometimes.  One is a `draft` and one is `pre-release`.  What am I doing wrong?  Here's my `jreleaser.yml`:

```yml
project:
  name: bottlerocket
  version: 0.42.0-SNAPSHOT
  snapshot:
    pattern: .*-SNAPSHOT
    label: "{{projectVersionNumber}}-SNAPSHOT"
    fullChangelog: true
  description: BottleRocket is an API to create MongoDB clusters in a variety shapes.
  copyright: 2020
  links:
    homepage: https://github.com/{{repoOwner}}/{{repoName}}
    documentation: https://github.com/{{repoOwner}}}/{{repoName}}
    license: https://github.com/{{repoOwner}}/{{repoName}}/blob/master/LICENSE

release:
  github:
    enabled: true
    owner: evanchooly
    name: bottlerocket
    username: evanchooly
    tagName: r{{projectVersionNumber}}
    releaseName: Release {{tagName}}
    commitAuthor:
      name: evanchooly
      email: jlee@antwerkz.com
    overwrite: true
    update:
      enabled: true
    changelog:
      enabled: true
    milestone:
      name: "{{tagName}}"
      close: false
    prerelease:
      enabled: true
    draft: false
    releaseNotes:
      enabled: false

files:
  enabled: true
  active: always
  globs:
    - pattern: target/bottlerocket-0.42.0-SNAPSHOT*.jar

upload:
  enabled: true
```

**Comment by evanchooly** [comment]
I've tweaked my config slightly and now I'm just getting a new 'draft' release each time rather than updating/overwriting the existing one.

```yml
project:
  name: bottlerocket
  version: 0.42.0-SNAPSHOT
  snapshot:
    pattern: .*-SNAPSHOT
    label: "{{projectVersionNumber}}-SNAPSHOT"
    fullChangelog: true
  description: BottleRocket is an API to create MongoDB clusters in a variety shapes.
  copyright: 2020

release:
  github:
    enabled: true
    owner: evanchooly
    name: bottlerocket
    username: evanchooly
    tagName: r{{projectVersionNumber}}
    releaseName: Release {{tagName}}
    commitAuthor:
      name: evanchooly
      email: jlee@antwerkz.com
    overwrite: true
    update:
      enabled: true
    changelog:
      enabled: true
    milestone:
      name: "{{tagName}}"
      close: false
    draft: true
    releaseNotes:
      enabled: false

files:
  enabled: true
  active: always
  globs:
    - pattern: target/bottlerocket-0.42.0-SNAPSHOT*.jar

upload:
  enabled: true
```
