### DISCUSSION TITLE
Override hardcoded /repo while releasing to github enterprise

### DISCUSSION THREAD

**Discussion by Nj-kol** [jreleaser/jreleaser#1148] [Q&A]
I am using GitHub enterprise, and while releasing it is using a different URL than what is provided. 

Sample config I am using :

```yaml
release:
  github:
    enabled : true
    host: github.dev.global.someorg.org
    repoUrl: https://github.dev.global.someorg.org/<employee_id>/hello-world
    owner: <employee_id>
    apiEndpoint : https://github.dev.global.someorg.org/
    overwrite: true
    sign: false
    changelog:
      formatted: 'ALWAYS'
      format: '- {{commitShortHash}} {{commitTitle}}'
      preset: 'conventional-commits'
      contributors:
        format: '- {{contributorName}}{{#contributorUsernameAsLink}} ({{.}}){{/contributorUsernameAsLink}}'
```

The error it gives is - 

```shell
[INFO]  Deploying is not enabled. Skipping
[INFO]  Uploading is not enabled. Skipping
[INFO]  Releasing to https://github.dev.global.someorg.org/<employee_id>/hello-world
[INFO]  Writing output properties to out/jreleaser/output.properties
[ERROR] JReleaser failed after 2.240 s
Unexpected error when creating release
org.kohsuke.github.HttpException: Server returned HTTP response code: 200, message: 'null' for URL: https://github.dev.global.someorg.org/repos/<employee_id>/hello-world
```

Notice the additional `/repo` being appended to the URL which I m not providing

**Comment by aalmiray** [comment]
The `/repos` path is added automatically by the hub4j library. What's ofd is that the library returns 200 but there's an  error. Unfortunately the message was not set and the output shows `null` as a result. 

One possible cause is the use of an access token with not enough permissions. Or the GHE instance requires a different authentication mechanism than the one JReleaser currently expects. 

Without exposing any private information, could you let me know what authentication methods are configured or expected by the GHE instance you're using?

**Reply by Nj-kol** [reply]
Thank you so much for your reply. Actually after a lot of trial and error, I found the solution. For our corporate repository, the prefix path was `/api/v3/` i.e. repos are of form `https://github.dev.global.someorg.org/api/v3/repos/<employee_id>/hello-world`

So changing my yaml  to ooks like below, worked for me :

```yaml
release:
  github:
    enabled : true
    host: github.dev.global.someorg.org
    owner: <employee_id>
    apiEndpoint : https://github.dev.global.someorg.org/api/v3
    overwrite: true
    sign: false
    changelog:
      formatted: 'ALWAYS'
      format: '- {{commitShortHash}} {{commitTitle}}'
      preset: 'conventional-commits'
      contributors:
        format: '- {{contributorName}}{{#contributorUsernameAsLink}} ({{.}}){{/contributorUsernameAsLink}}'
```
