### DISCUSSION TITLE
Problem with changelog replacers

### DISCUSSION THREAD

**Discussion by silvanbrenner** [jreleaser/jreleaser#1172] [Q&A]
Hi all

I've some problem to replace our Issue with Links inside changelog.
I tried the following 2 replacers:

```
changelog:
    formatted: ALWAYS
    preset: 'conventional-commits'
    format: '- {{commitShortHash}} {{commitTitle}}'
    replacers:
      - search: 'ISSUE-(\d{1,10})'
        replace: '[ISSUE-$1](https://ticket.com/ISSUE-$1)'
      - search: '/ISSUE-(\d{1,10})/g'
        replace: '[ISSUE-$1](https://ticket.com/ISSUE-$1)'
```

The first one find the issue, but not replace the regex groups. So the result is some like "[ISSUE-](https://ticket.com/ISSUE-)". The number is missing.
The second approach find nothing to replace.

Anyone a hint?
Thanks!

**Comment by aalmiray** [comment]
Could you paste the output of `jreleaser -V` if you're using the CLI? Otherwise `mvn --version` or `gradle --version` if you're using  the plugin for any of those build tools. Thanks.

**Reply by silvanbrenner** [reply]
I'm using the docker image jreleaser-slim:v1.4.0

> ------------------------------------------------------------
> jreleaser 1.4.0
> ------------------------------------------------------------
> Build time:   2022-12-29 15:08:38Z
> Revision:     b977b66baed1e4761af054c5d747a0804f457252
> JVM:          17.0.2 (Azul Systems, Inc. 17.0.2+8-LTS)
> ------------------------------------------------------------

**Reply by aalmiray** [reply]
Just tried the following. On a repository with these commits:

```
* d7ae821 (HEAD -> main) ISSUE-12345: Fix release configuration
* 6107063 ISSUE-1: Fix pom
* 4df324c (origin/main, origin/HEAD) chore: Update JReleaser configuration
* 035c613 fix: Update JReleaser configuration
* 19742db feat: Add arguments to Main class
* b2f44ae fix: Use fetch-depth=0 when checking out on release
* 420029a feat: Add Maven assembly descriptor
* 91ce213 chore: Setup build & release workflows
* bcb9a13 feat: Add JReleaser configuration
* 1294493 chore: Add Maven wrapper files
* 75dab0f chore: Add sources
* 532b93b chore: Add license file
* 51c3234 Init repository
```

Running JReleaser 1.4.0 CLI on OSX

```
------------------------------------------------------------
jreleaser 1.4.0
------------------------------------------------------------
Build time:   2022-12-29 15:08:38Z
Revision:     b977b66baed1e4761af054c5d747a0804f457252
JVM:          1.8.0_352 (Azul Systems, Inc. 25.352-b08)
------------------------------------------------------------
```

With this configuration

```yml
project:
  name: app
  description: Sample application
  longDescription: Sample application
  links:
    homepage: https://acme.com/wesome-app
  authors:
    - Andres Almiray
  license: Apache-2.0
  java:
    groupId: com.acme
    version: 8
  inceptionYear: 2022

release:
  github:
    overwrite: true
    sign: true
    changelog:
      formatted: ALWAYS
      preset: 'conventional-commits'
      format: '- {{commitShortHash}} {{commitTitle}}'
      replacers:
        - search: 'ISSUE-(\d{1,10})'
          replace: '[ISSUE-$1](https://ticket.com/ISSUE-$1)'
```

Yields the following changelog:

```
## Changelog

## 🚀 Features
- 19742db feat: Add arguments to Main class
- 420029a feat: Add Maven assembly descriptor
- bcb9a13 feat: Add JReleaser configuration

## 🐛 Fixes
- 035c613 fix: Update JReleaser configuration
- b2f44ae fix: Use fetch-depth=0 when checking out on release

## 🧰 Tasks
- 4df324c chore: Update JReleaser configuration
- 91ce213 chore: Setup build & release workflows
- 1294493 chore: Add Maven wrapper files
- 75dab0f chore: Add sources
- 532b93b chore: Add license file

---
- d7ae821 [ISSUE-12345](https://ticket.com/ISSUE-12345): Fix release configuration
- 6107063 [ISSUE-1](https://ticket.com/ISSUE-1): Fix pom
- 51c3234 Init repository


## Contributors
We'd like to thank the following people for their contributions:
Andres Almiray
```

Next, tried running with the docker image such as 
```docker run -it --rm -e JRELEASER_GITHUB_TOKEN=<secret> -e JRELEASER_PROJECT_VERSION=1.0.0 -v `(pwd)`:/workspace jreleaser/jreleaser-slim:v1.4.0 changelog -g``` and got the same result that is, the replacer is working as expected.
