### DISCUSSION TITLE
launcher script for the module path

### DISCUSSION THREAD

**Discussion by bmarwell** [jreleaser/jreleaser#1245] [Ideas]
Hey!

I want to bundle an application using the "bin" option which uses the module path where applicable.

However, the launcher script only supports the class path at the moment:
https://github.com/jreleaser/jreleaser/blob/7ed38b21da3d1f4ceafb2b2eeb8192580191696f/core/jreleaser-templates/src/main/resources/META-INF/jreleaser/templates/java-archive/java-archive/bin/launcher.tpl

The next question is: How does jreleaser know which jar goes into which directory (lib vs modules)? I haven't seen any maven plugin to support this either. the appimage-maven-plugin does not, nor the maven-assembly-plugin if I am not mistaken.

**Comment by aalmiray** [comment]
To signal the `java-archiver` that the application is modular you must define both `mainModule` and `mainClass` parameters, such as

```yaml
project:
  version: 1.0.0

assemble:
  javaArchive:
    app:
      active: ALWAYS
      fileSets:
        - input: '.'
          includes:
            - 'LICENSE'
            - 'README'
      mainJar:
        path: target/{{distributionName}}-{{projectVersion}}.jar
      java:
        mainClass: com.acme.Main
        mainModule: com.acme
```

I'll update the guide with this example.

Regarding the 2nd question, at the moment the application is either modular or not. However, all JARs are placed under the `lib` directory. If the application is modular then the launcher script will use the modulepath, otherwise classpath is used.
