### DISCUSSION TITLE
Maven Central deploy fails because sources/javadocs jar of empty jar is missing.

### DISCUSSION THREAD

**Discussion by ge0ffrey** [jreleaser/jreleaser#1287] [Q&A] [answered]
I am trying to release with JReleaser to Maven Central and getting these kinds of errors:

```
[ERROR]    [nexus2] optaplanner-spring-boot-starter-8.36.0.Alpha1-sources.jar is missing
[ERROR]    [nexus2] optaplanner-spring-boot-starter-8.36.0.Alpha1-javadoc.jar is missing
[ERROR]    [nexus2] optaplanner-ide-config-8.36.0.Alpha1-javadoc.jar is missing
```

The sources and javadoc plugins are active and **Maven Central has accepted these artifacts for years**.

However these modules are special:

- optaplanner-spring-boot-starter has no src directory. It just depends on optaplanner-spring-boot-autoconfigure, optaplanner-core and optaplanner-persistence-jackson. So the maven plugins don't create a sources nor a javadocs jar.
- optaplanner-ide-config has no java files. So the maven plugins don't create a javadocs jar.

How do I fix this?

**Comment by ge0ffrey** [comment]
I created these issues on pomchecker:

- https://github.com/kordamp/pomchecker/issues/10
- https://github.com/kordamp/pomchecker/issues/11

How do I workaround this meanwhile?

**Reply by aalmiray** [reply]
There's no workaround at the moment that would let you release staged artifacts as you have them, as JReleaser runs with strict checks. See https://github.com/jreleaser/jreleaser/blob/20c43d43c837e1317d0e43879a636bc77944a1bf/sdks/jreleaser-java-sdk-commons/src/main/java/org/jreleaser/sdk/commons/AbstractMavenDeployer.java#L159-L178

The [ugly] workaround is to create empty `-sources` and `-javadoc` JARs for the time being. Or switching to Maven's deploy and nexus-staging plugins til we find a better solution in JReleaser.

Perhaps adding the following DSL elements in the future:

```yaml
deploy:
  maven:
    nexus2:
      maven-central:
        active: always
        url: https://s01.oss.sonatype.org/service/local
        closeRepository: true
        releaseRepository: true
        requireSourcesJar: true | false
        requireJavadocJar: true | false
        artifactOverrides:
          - groupId: com.acme
            artifactId: foo
            requireSourcesJar: true | false
            requireJavadocJar: true | false
        stagingRepositories:
          - target/staging-deploy
```

This would allow setting sources/javadoc requirements for all artifacts or target individual artifacts matching GAV coordinates. WDYT?
