### DISCUSSION TITLE
How to sign tags created by JReleaser?

### DISCUSSION THREAD

**Discussion by algomaster99** [jreleaser/jreleaser#1384] [Q&A]
Here is my config from `trace.log`

```yml
release:
    github:
        enabled: true
        host: github.com
        owner: algomaster99
        name: next-semver
        username: algomaster99
        token: ************
        artifacts: true
        files: true
        checksums: true
        catalogs: true
        signatures: true
        repoUrl: https://{{repoHost}}/{{repoOwner}}/{{repoName}}
        repoCloneUrl: https://{{repoHost}}/{{repoOwner}}/{{repoName}}.git
        commitUrl: https://{{repoHost}}/{{repoOwner}}/{{repoName}}/commits
        srcUrl: https://{{repoHost}}/{{repoOwner}}/{{repoName}}/blob/{{repoBranch}}
        downloadUrl: https://{{repoHost}}/{{repoOwner}}/{{repoName}}/releases/download/{{tagName}}/{{artifactFile}}
        releaseNotesUrl: https://{{repoHost}}/{{repoOwner}}/{{repoName}}/releases/tag/{{tagName}}
        latestReleaseUrl: https://{{repoHost}}/{{repoOwner}}/{{repoName}}/releases/latest
        issueTrackerUrl: https://{{repoHost}}/{{repoOwner}}/{{repoName}}/issues
        tagName: {{projectVersion}}
        releaseName: {{tagName}}
        branch: main
        branchPush: main
        commitAuthor:
            name: jreleaserbot
            email: jreleaser@kordamp.org
        sign: true
        skipTag: false
        skipRelease: false
        overwrite: false
        update:
            enabled: false
        apiEndpoint: https://api.github.com
        connectTimeout: 20
        readTimeout: 60
        changelog:
            enabled: true
            append:
                enabled: false
            links: false
            skipMergeCommits: false
            sort: DESC
            formatted: ALWAYS
            preset: conventional-commits
            format: - {{commitShortHash}} {{commitTitle}}
            categoryTitleFormat: ## {{categoryTitle}}
            contributorsTitleFormat: ## Contributors
            content:  ...

signing:
    enabled: true
    active: ALWAYS
    armored: true
    verify: true
    mode: MEMORY
    artifacts: true
    files: true
    checksums: true
    catalogs: true
    passphrase: ************
    publicKey: ************
    secretKey: ************
```

As you can see `sign` under `release` is set to `true`. How do I provide GPG keys for signing my tags? Note that I am already signing the jar files that I upload on maven central. 

Reference repository: https://github.com/algomaster99/next-semver/releases
