### DISCUSSION TITLE
Support common server definitions

### DISCUSSION THREAD

**Discussion by aalmiray** [jreleaser/jreleaser#1394] [Ideas]
There are multiple DSL elements where duplicate information is required: release, deploy, upload, download. Supporting multiple issue trackers will add more duplication (#1209). Thus it makes sense to define common server configuration at a single location.

An idea discussed at Hackergarten Zurich May 2023 is to define the following DSL section:

```yaml
servers:
  mygithub:
    type: GITHUB
    host: https://acme.com
    username: foobar
    password: secret
```

The `type` property must be a valid value of a `ServerType` enum that enumerates all supported server types. A server is a remote service supporting 3 properties: `host`, `username`, `password`. A concrete consumer of a server may map `password` to another property such as `token`, this happens internally.

Server consumers must declare their intention to consume a named service, for example

```yml
release:
  github:
    server: mygithub
```

### Type specific properties

These properties may be defined at the `servers` section using `extraProperties`, such that

```yaml
servers:
  mygithub:
    type: GITHUB
    extraProperties:
      discussionCategoryName: 'Announcements'

release:
  github:
    server: mygithub
```

Would be equivalent to defining the following in `v1.6.0`:

```yaml
release:
  github:
    discussionCategoryName: 'Announcements'
```

Hackergarten participants: @liquidice95, @jwloka, @nonzerogeoduck7

## Open Questions

- Should servers support more specific properties? The suggested properties (`host`, `username`, `password`) are enough for most services, however this leaves out SSH, SCP, and SFTP who share other common properties such as `publicKeyFile` and `fingerprint` for example. If so, these additional properties may be added to the generic `Server` type _or_ more specific server types should be added, in which case the suggested DSL should reflect that:
 
```yaml
servers:
  http:
    mygithub:
      host: https://acme.com
      username: foobar
      password: secret
  ssh:
    myssh:
      host: https://acme.com
      username: foobar
      fingerprint: '34:56:78:12:45:67'
```

Mixing all properties on a single `Server` type leads to

```yaml
servers:
  mygithub:
    type: GITHUB
    host: https://acme.com
    username: foobar
    password: secret
  myssh:
    type: SSH
    host: https://acme.com
    username: foobar
    fingerprint: '34:56:78:12:45:67'
```

Validation by `type` could raise warnings or errors if a unsupported property for a given type (`fingerprint` for `GITHUB`0 were to be explicitly configured.
