### DISCUSSION TITLE
Can I use without ${{ secrets.GITHUB_TOKEN }} ??

### DISCUSSION THREAD

**Discussion by melloware** [jreleaser/jreleaser#1488] [Q&A] [answered]
I have this build:

https://github.com/open-sce/fluent-cli/blob/main/.github/workflows/early-access.yml

Its failing because the GitHub Token is not set because this is an organization to which I don't own the repo settings and is managed by a larger organization.

They recommended I try using packages:write like..

```yml
release:
    needs: [ build ]
    runs-on: ubuntu-latest
    permissions:
      packages: write
```

But this did not work either as you can see from this build output: https://github.com/open-sce/fluent-cli/actions/runs/6149737520/job/16686451088

Do I have any recourse to make Jreleaser work?
