### DISCUSSION TITLE
Customising JLink launcher template variables

### DISCUSSION THREAD

**Discussion by jvalkeal** [jreleaser/jreleaser#1498] [General]
With #1496 I was trying to find if there's a workaround to set `distributionJavaMainJar` manually with extra properties. Turned out that as jlink assembly is done at "assembly" time, extra properties from `jreleaser.yml` would simply set variable name `jlinkJavaMainJar` which is useless for jlink's `launcher.tpl`.

This being something like:
```
assemble:
  jlink:
    foobar:
      extraProperties:
        javaMainJar: xxx
```

I was just thinking if I've missed something and if there's an actual workaround.

Naively I also tried:

```
distributions:
  jlink:
    foobar:
      extraProperties:
        javaMainJar: xxx
```
Which would actually set `distributionJavaMainJar` but it's too late in a game to get used in an assemble phase.
