### DISCUSSION TITLE
IndividualChecksum property of single JAR distribution is set to true by default

### DISCUSSION THREAD

**Discussion by charphi** [jreleaser/jreleaser#1511] [Q&A] [answered]
### Steps to Reproduce

1. Create a POM config with a single JAR distribution
2. Do not specify anywhere that individual checksum should be used

### Expected Behaviour

`IndividualChecksum` property of single JAR distribution should be false by default.

### Actual Behaviour

`IndividualChecksum` property of single JAR distribution is set to true by default.

### Environment Information

- **Operating System**: Ubuntu
- **JReleaser Version:** 1.8.0
- **JDK Version:** 17

Trace log:
```
distributions:
    hello-nbbrd:
        enabled: true
        active: ALWAYS
        type: SINGLE_JAR
        executable:
            name: hello-nbbrd
            windowsExtension: bat
        platform:
        artifacts:
            artifact 0:
                enabled: true
                active: ALWAYS
                path: /home/runner/work/sandbox/sandbox/sandbox-cli/target/sandbox-cli-2.3.3-bin.jar
                extraProperties:
                    individualChecksum: true
        stereotype: NONE
```

Pom config:
```xml
<distributions>
    <!-- Name is here ! -->
    <hello-nbbrd>
        <type>SINGLE_JAR</type>
        <artifacts>
            <artifact>
                <path>
                    ${project.parent.basedir}/sandbox-cli/target/sandbox-cli-${project.version}-bin.jar
                </path>
            </artifact>
        </artifacts>
        <java>
            <mainClass>nbbrd.sandbox.cli.MainCommand</mainClass>
            <artifactId>sandbox-cli</artifactId>
        </java>
        <scoop>
            <active>RELEASE</active>
        </scoop>
        <brew>
            <active>RELEASE</active>
        </brew>
        <jbang>
            <active>RELEASE</active>
        </jbang>
    </hello-nbbrd>
    ...
</distributions>
```

See https://github.com/nbbrd/sandbox/blob/ef1a15e8eaa2d6b21c32aada85327b933a8e0c6f/sandbox-bom/pom.xml#L196
