### DISCUSSION TITLE
Generated release with JBang as a packager fails when you run the script.

### DISCUSSION THREAD

**Discussion by dcolina** [jreleaser/jreleaser#1512] [Q&A] [answered]
Context:

I've built a Quarkus Picocli (hello world) application, and it was released with JReleaser 1.8.0 version, and it has setup JBang as packager.

```
# Generated with JReleaser 1.8.0 at 2023-09-05T09:49:01.355976+02:00
project:
  name: qcli-jbang
  description: app -- Sample Quarkus CLI application
  longDescription: app -- Sample Quarkus CLI application
  versionPattern: 'CUSTOM:0Y.0M.MICRO'
  stereotype: CLI
  java:
    mainClass: com.dotcms.GreetingCommand
  copyright: |
    The Apache-2.0 License
  license: Apache-2.0
  links:
    homepage: https://www.qcli-jbang.com
    documentation: https://www.qcli-jbang.com/docs/latest
  authors:
    - dotCMS

release:
  github:
    tagName: 'v{{projectVersion}}'
    releaseName: '{{projectVersion}}'
    overwrite: true
    changelog:
      formatted: ALWAYS
      format: '- {{commitShortHash}} {{commitTitle}}'
      preset: conventional-commits
      contributors:
        format: '- {{contributorName}}'
      hide:
        categories:
          - merge
        contributors:
          - GitHub
          - dependabot

distributions:
  qcli-jbang:
    type: SINGLE_JAR
    active: ALWAYS
    stereotype: CLI
    artifacts:
      - path: target/{{distributionName}}-{{projectVersion}}-runner.jar
        transform: target/{{distributionName}}-{{projectVersion}}.jar

packagers:
  jbang:
    alias: qcli
    active: ALWAYS
    continueOnError: false

```

After released we have the following files.

```
-rwxrwxrwx  1 dcolina  staff   149B Oct 18 13:30 jbang-catalog.json
-rwxrwxrwx  1 dcolina  staff   301B Oct 18 13:30 qcli_jbang.java
```

```
❯ cat jbang-catalog.json
{
  "aliases": {
    "qcli-jbang": {
      "script-ref": "qcli_jbang.java",
      "description": "app -- Sample Quarkus CLI application"
    }
  }
}
```

```
❯ cat qcli_jbang.java
//usr/bin/env jbang "$0" "$@" ; exit $?
//JAVA 11+
//DEPS com.dotcms:qcli-jbang:1.0.0
// Generated with JReleaser 1.8.0 at 2023-10-18T13:30:20.588194+02:00

public class qcli_jbang {
    public static void main(String... args) throws Exception {
        com.dotcms.GreetingCommand.main(args);
    }
}
```

When I try to run `./qcli_jbang.java` I got the following error:

```
❯ ./qcli_jbang.java
[jbang] Building jar for qcli_jbang.java...
/Users/dcolina/dotcms-projects/training/quarkus/qcli-jbang/target/jreleaser/package/qcli-jbang/jbang/qcli_jbang.java:8: error: cannot find symbol
        com.dotcms.GreetingCommand.main(args);
                                  ^
  symbol:   method main(String[])
  location: class GreetingCommand
1 error
[jbang] [ERROR] Error during compile
[jbang] Run with --verbose for more details
```

I don't know what to do to solve this problem. Can anyone give me a tip or advise to solve this issue?
