### DISCUSSION TITLE
Add support to extract issues from commit-body in changelog

### DISCUSSION THREAD

**Discussion by ahoehma** [jreleaser/jreleaser#1537] [Ideas]
My commits may contain jira-issues like FOO-12345.

It would be nice to have a placeholder **issueId** and **issueLink** to be used like this:

format: '* {{commitShortHash}} {{commitTitle}} [{{issueId}}]({{issueLink}})'

May I can define a issueServerUrlPrefix and includes for issue-patterns:

```
issues:
  serverUrlPrefix: "http://jira-server/browse/"
  includes:
    - "CC-\d+"
    - "PRO-\d+"
    - "FOO-\d+"
```

**Comment by aalmiray** [comment]
There may be more than one target tracker in a given commit message, for example if a project uses both JIRA and GitHub issues. I'd say it would be better to set a list of potential matchers, with a single URL as target, such that

```
issues:
  - url: http://jira-server/browse
    pattern:
    - 'CC-\d+'
    - 'PRO-\d+'
    - 'FOO-\d+'
  - pattern:
    - '#\d+'
```

The second entry matches short GitHub issue mentions and assumes the default issue tracker to be the same as the one associated with the current releaser (GitHub).

Related to 

 - https://github.com/jreleaser/jreleaser/issues/1209
 - https://github.com/jreleaser/jreleaser/discussions/1394
