### DISCUSSION TITLE
Conventional commits changelog customisation

### DISCUSSION THREAD

**Discussion by jponge** [jreleaser/jreleaser#1608] [Q&A] [answered]
Hi,

I'm using conventional commits and would like to have a dedicated category for tests (`test: XYZ`) rather than them ending in the default "build" category.

I tried the following Maven configuration tweaks, but to no avail:

```xml
<labelers>
    <labeler>
        <label>test</label>
        <title>regex:test:</title
    </labeler>
</labelers>
<categories>
    <category>
        <title>🧪Tests</title>
        <key>test</key>
        <labels>test</labels>
        <order>110</order>
    </category>
</categories>
```

What am I doing wrong? Thanks!

**Comment by aalmiray** [comment]
As far as I can tell the `test` label is applied automatically to the `Build` category as seen when evaluating the configuration. There's also a `test` labeler found by default:

```yaml
            categories:
                ...
                category 5:
                    key: build
                    title: 🛠  Build
                    labels:
                        test
                        build
                        ci
                    order: 50
            labelers:
                ...
                labeler 2:
                    label: build
                    title: regex:^(?:build(?:\(.*\))?!?):\s.*
                    order: 10
                ...
                labeler 12:
                    label: test
                    title: regex:^(?:test(?:\(.*\))?!?):\s.*
                    order: 110
```

This is indeed a problem as the `test` label should not be applied to the `Build` category, and we're missing a `Test` category.

The current workaround is to define a `Test` category with a negative `order` such as `-1` so that it gets evaluated first.
