### DISCUSSION TITLE
Maven Central Android Gradle deploy example. Sign issue

### DISCUSSION THREAD

**Discussion by LionZXY** [jreleaser/jreleaser#1679] [Q&A] [answered]
I couldn't find any example for deploy an Android library on Maven Central via jreleaser+gradle. 
I tried to do it myself, but unfortunately I'm stumped. I can't figure out how jReleaser signs the files. I get a file signing error when I try to release an Android library:
```
pkg:maven/uk.kulikov/slf4j2-timber@0.2?type=aar Missing signature for file: slf4j2-timber-0.2-javadoc.jar
pkg:maven/uk.kulikov/slf4j2-timber@0.2?type=aar Missing signature for file: slf4j2-timber-0.2-sources.jar
pkg:maven/uk.kulikov/slf4j2-timber@0.2?type=aar Missing signature for file: slf4j2-timber-0.2.aar
pkg:maven/uk.kulikov/slf4j2-timber@0.2?type=aar Missing signature for file: slf4j2-timber-0.2.module
pkg:maven/uk.kulikov/slf4j2-timber@0.2?type=aar Missing signature for file: slf4j2-timber-0.2.pom
```

[Here](https://github.com/LionZXY/slf4j2-timber/blob/7d248f379aea8433ad55b6287a6677051969b5ee/slf4j2-timber/build.gradle.kts#L116) you can see how I configured the plugin 

The questions proper are:
- Where to see/set debug point where files are signed for Deploy?
- Why does Maven Central tell me that the files are not signed?
Also: pomchecker is broken and doesn't work correctly on `aar`:
`[ERROR] Unknown packaging: aar @ line 13, column 14`

**Comment by aalmiray** [comment, marked as answer]
Do you have access to `build/jreleaser/trace.log`? It shows the resolved model plus a full log of everything the tool did in that run. 

A quick glance at the config seems to show everything in order. Will check why PomChecker complained. I'll release a patch soon enough if there's a bug. 

Also, invoking the setter for auth in the mavenCentral deployer should not be needed. Did the configuration fail without it?

**Reply by aalmiray** [reply]
There's indeed a bug in pomchecker. Filed https://github.com/kordamp/pomchecker/issues/21

**Reply by LionZXY** [reply]
Attached the log and the bandle that is being created:
[trace.log](https://github.com/user-attachments/files/16011871/trace.log)
[slf4j2-timber-root-0.2-bundle.zip](https://github.com/user-attachments/files/16011869/slf4j2-timber-root-0.2-bundle.zip)

**Reply by aalmiray** [reply]
Note that you need a maven plugin configured in the pom that can resolve the `aar` packaging instruction.

**Reply by LionZXY** [reply]
Do you know how to add it?

**Reply by aalmiray** [reply]
Given that you're using Gradle you must add an action that configures the generated pom, similarly as it's shown at https://stackoverflow.com/questions/17281927/how-to-make-gradle-generate-a-valid-pom-xml-file-at-the-root-of-a-project-for-ma

**Reply by LionZXY** [reply]
I solved the signature error by adding this code block. It's logical, but I didn't think of that - I thought jReleaser should sign it:
```
signing {
    val signingSecretKey = System.getenv("JRELEASER_GPG_SECRET_KEY")
    val signingPasskey = System.getenv("JRELEASER_GPG_PASSPHRASE")
    useInMemoryPgpKeys(signingSecretKey, signingPasskey)
    sign(publishing.publications.getByName("release"))
}
```

**Reply by aalmiray** [reply]
Now, regarding the missing signature files. Inspecting the resolved model found in the trace log shows 

```

deploy:
    enabled: true
    active: ALWAYS
    maven:
        enabled: true
        active: ALWAYS
        pomchecker:
            version: 1.11.0
            failOnWarning: true
            failOnError: true
        mavenCentral:
            sonatype:
                enabled: true
                active: ALWAYS
                connectTimeout: 20
                readTimeout: 60
                authorization: BASIC
                url: https://central.sonatype.com/api/v1/publisher
                username: ************
                password: ************
                sign: false
                checksums: false
                sourceJar: false
                javadocJar: false
                verifyPom: false
                applyMavenCentralRules: false
```

This shows that signing is turned `off` because applyMavenCentralRules was set to `false`, probably to get around the problem of resolving `aar` as packaging. You can explicitly turn signing `on`.
