### DISCUSSION TITLE
Pom checker fail with kotlin multiplatform

### DISCUSSION THREAD

**Discussion by ygdrasil-io** [jreleaser/jreleaser#1705] [Q&A]
Hello, I'm trying to publish a Kotlin Multiplatform library, but I'm encountering errors like:
```
[INFO]      [mavenCentral] Verifying POMs

[ERROR]     [mavenCentral] java.lang.IllegalStateException: org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[ERROR]     [mavenCentral] [ERROR] Unknown packaging: klib @ line 12, column 14
```

I tried to disable the POM checker, but it didn't work :
```kotlin
jreleaser {
    gitRootSearch = true

    project {
        description = libraryDescription
        copyright = "MIT"
    }

    signing {
        active = Active.ALWAYS
        armored = true
        artifacts = true
    }

    deploy {
        active = Active.ALWAYS
        maven {

            pomchecker {
                active = Active.NEVER
                failOnError = false
            }

            active = Active.ALWAYS
            mavenCentral {
                active = Active.ALWAYS
                create("sonatype") {
                    stage = Stage.UPLOAD
                    active = Active.ALWAYS
                    url = "https://central.sonatype.com/api/v1/publisher"
                    stagingRepository("build/staging-deploy")
                }
            }
        }
    }
}
```

Any idea how to fix that ?

**Comment by aalmiray** [comment]
It looks like `klib` is not a supported packaging option. Personally never heard of it, don't know what are the constraints wrt sources & javadocs, and other related artifacts. Do you have access to the trace.log found in out/jreleaser?

**Reply by ygdrasil-io** [reply]
`klib` are non-jvm (JS, WASM and Native) artifacts on kotlin ecosystem and they are publish on maven central also. 
I think that logs file are not available on github CI, I will reproduce localy and get back to you.

**Reply by aalmiray** [reply]
A few things regarding your experiments:

1. the `pomchecker` section does not support the `active` property. I'm surprised you didn't get an error due to a missing property exception. IOW this should fail no matter what. 
```
            pomchecker {
                active = Active.NEVER
                failOnError = false
            }
```

2. Disabling pomchecker can be done by setting the `verifyPom` property of the deployer to `false`
```
deploy:
  maven:
    nexus2:
      maven-central:
        active: ALWAYS
        url: https://s01.oss.sonatype.org/service/local
        snapshotUrl: https://s01.oss.sonatype.org/content/repositories/snapshots/
        closeRepository: false
        releaseRepository: false
        verifyPom: false
        stagingRepositories:
          - target/staging-deploy
```

3. Pomchecker requires building a full model of a target pom.xml. This file must be fully resolvable which means there should be a plugin configured in the pom that can resolve the `klib` packaging definition. Disabling pomchecker will let you continue but the pom may be missing some pieces and Maven Central will complain.

This being said, I think skipping a given pom and not all may be a good idea. Maven deployers already have the option to define artifact overrides per GAV (such as skipping -sources and -javadoc) thus adding support for skipping pom checks could be done without much fuzz.
