### DISCUSSION TITLE
How to use jreleaser for maven central deployment only?

### DISCUSSION THREAD

**Discussion by mewim** [jreleaser/jreleaser#1725] [Q&A] [answered]
Hi,
I am looking to publish to Maven Central. Since JReleaser is recommended on https://central.sonatype.org/publish/publish-portal-gradle/, I am giving it a try. In my Gradle file I have:

```
jreleaser {
    release {
        github {
            enabled = false
        }
    }
    gitRootSearch = true
    signing {
        active = 'ALWAYS'
        armored = true
    }
    deploy {
        maven {
            mavenCentral {
                sonatype {
                    active = 'ALWAYS'
                    url = 'https://central.sonatype.com/api/v1/publisher'
                    stagingRepository('target/staging-deploy')
                }
            }
        }
    }
}
```

However, this fails to work, complaining `No release provider has been configured`. Since we have already established a workflow to release to GitHub, we do not want JReleaser to release anything to our GitHub repo and we also do not want to provide a GitHub token. Only publishing to Maven Central is what we need. Is there a method to configure JReleaser this way?

**Comment by aalmiray** [comment, marked as answer]
For the time being a single releaser must be configured. You don't have to use it to post releases to GitHub but it does have to exist and be enabled. You also don't have to provide a valid GITHUB_TOKEN, just a non empty one.

Perhaps on the future this constraint may be relaxed if `deploy` is invoked and no release information is required.

**Reply by mewim** [reply]
Thanks for your reply. How do I disable all the publishing behavior for GitHub? Do I need to configure individually for each option?

**Reply by aalmiray** [reply]
You may set `skipRelease` to `true` in the `github` releaser.

**Comment by jmini** [comment]
Is this still accurate?

```
jreleaser {
    // ... signing, and deploy configured
    release {
        github {
            skipRelease = true
        }
    }
}
```

Requires  the token to be set:

> `release.github.token` must not be blank. Configure a value using the Gradle DSL, or define a System property `jreleaser.github.token`, or define a `JRELEASER_GITHUB_TOKEN` environment variable, or define a key/value pair in `~/.jreleaser/config.toml` with a key named `JRELEASER_GITHUB_TOKEN`

Using jreleaser `1.19.0`...

**Reply by aalmiray** [reply]
Yes, setting `skipRelease` to `true` still required a non-empty token. The value could be gibberish if you only want to deploy. 

The other way is to set `enabled` to `false` instead of setting `skipRelease`.

What's the difference? `enabled` controls the whole feature (changelog, tagging, posting, upload) while `skipRelease` controls a smaller feature, mainly posting the release to GH.

**Reply by aalmiray** [reply]
This is the minimum configuration required for deployment **only**

```yaml
project:
  version: '1.0.0'
  name: helloworld
  languages:
    java:
      groupId: org.jreleaser.examples

signing:
  active: ALWAYS
  armored: true

deploy:
  maven:
    mavenCentral:
      sonatype:
        active: ALWAYS
        url: https://central.sonatype.com/api/v1/publisher
        stagingRepositories:
          - target/staging-deploy

release:
  github:
    enabled: false
```
