### DISCUSSION TITLE
Difficulty Troubleshooting Cosign

### DISCUSSION THREAD

**Discussion by thebeanogamer** [jreleaser/jreleaser#1743] [Q&A] [answered]
@ml-james and I are running into issues setting up JReleaser and Cosign in GitHub Actions, could we have some help please? We're getting `[sign] cosign password does not match`, which appears to happen if you get any error back from `cosign public-key`.

https://github.com/jreleaser/jreleaser/blob/ee87b09053bf2fac44d5b7fa64114a581883a64c/sdks/jreleaser-tool-java-sdk/src/main/java/org/jreleaser/sdk/tool/Cosign.java#L48-L67

We've tried manually running `cosign public-key --key "<path to private key>"` and it outputs the public key as we'd expect, so we're at a bit of a loss.

```yaml
      - name: Write out Cosign Private Key for JReleaser
        run: echo "$COSIGN_PRIVATE_KEY" > cosign.pem
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
      - name: Print the Cosign Public Key to Confirm We Can
        run: cosign public-key --key "cosign.pem"
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
      - name: Validate that the public key exists
        run: test -f "${{ github.workspace }}/cosign.pub"
      - name: Publish package to Maven Central
        uses: gradle/gradle-build-action@v2.11.1
        with:
          arguments: jreleaserFullRelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.JRELEASER_MAVENCENTRAL_USERNAME }}
          JRELEASER_MAVENCENTRAL_TOKEN: ${{ secrets.JRELEASER_MAVENCENTRAL_TOKEN }}
          JRELEASER_COSIGN_PUBLIC_KEY: "${{ github.workspace }}/cosign.pub"
          JRELEASER_COSIGN_PRIVATE_KEY: "${{ github.workspace }}/cosign.pem"
          JRELEASER_COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          JRELEASER_GITHUB_TOKEN: ${{ github.token }}
```

Our actual JReleaser Signing config is pretty simple (although it's a best guess so may be wrong):

```groovy
jreleaser {
    files {
        active = 'ALWAYS'
        glob {
            pattern = 'build/staging-deploy/**/*.jar'
            pattern = 'build/staging-deploy/**/*.pom'
            pattern = 'build/staging-deploy/**/*.module'
        }
    }
    signing {
        active = 'ALWAYS'
        armored = true
        mode = 'COSIGN'
        verify = true
        cosign {
            version = '2.4.1'
        }
    }
    deploy {
        maven {
            mavenCentral {
                sonatype {
                    active = 'ALWAYS'
                    url = 'https://central.sonatype.com/api/v1/publisher'
                    stagingRepository('build/staging-deploy')
                    applyMavenCentralRules = true
                }
            }
        }
    }
}
```

Happy to share any extra information or logs, and thanks for making such a useful tool!
