### DISCUSSION TITLE
Hide bots from changelog

### DISCUSSION THREAD

**Discussion by dsgrieve** [jreleaser/jreleaser#1767] [Q&A] [answered]
First of all, I have gone through the other discussions on and around this topic. I cannot get the solution of adding a labeler and a category then hiding the category to work. The most puzzling piece is that there is another combination of labeler+category+hide which does work.

In my log I have entries that look like this: 

```
commit d37e883d4947e3d5883e26769e76a3211094c629
Author: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Date:   Fri Oct 25 16:20:39 2024 +1300

    Bump actions/checkout from 4.2.1 to 4.2.2 (#397)
    
    Bumps [actions/checkout](https://github.com/actions/checkout) from 4.2.1 to 4.2.2.
    - [Release notes](https://github.com/actions/checkout/releases)
    - [Changelog](https://github.com/actions/checkout/blob/main/CHANGELOG.md)
    - [Commits](https://github.com/actions/checkout/compare/eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871...11bd71901bbe5b1630ceea73d27597364c9af683)
    
    ---
    updated-dependencies:
    - dependency-name: actions/checkout
      dependency-type: direct:production
      update-type: version-update:semver-patch
    ...
    
    Signed-off-by: dependabot[bot] <support@github.com>
    Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
```

In my pom, I have a `<labeler/>` in `<lablerers/>`:
```
<labeler>
  <label>bots</label>
  <contributor>dependabot[bot]</contributor>
  <!-- <title>^Bump.+from.+to.+</title> -->
  <!-- <title>regex:Bump.*from.*to.*</title> -->
</labeler>
```

a `<category/>` in `<categories/>`:
``` 
<category>
  <title>bots</title>
   <labels>bots</labels>
 </category>
```

and `<categories/>` in `<hide\>
```
<categories>
  <category>maven-release</category>
  <category>bots</category>
</categories>
```

And yet my changelog has: 
` - d37e883 Bump actions/checkout from 4.2.1 to 4.2.2 (#397) (dependabot[bot])`

As you can see, I've tried a few different things for the labeler with no success. I must be missing something. Please help!

**Comment by aalmiray** [comment]
Did you try using the following:

```
<changelog>
  <hide>
    <contributors>
      <contributor>dependabot[bot]</contributor>
    </contributors>
  </hide>
</changelog>
```

This option does not rely on labelers/categories and should match contributors directly.

**Reply by dsgrieve** [reply]
Yes.  Indeed, this does keep `dependabot[bot]` from showing up in the list of contributors, but not in the list of changes. 
```
<hide>
    <contributors>
         <contributor>GitHub</contributor>
         <contributor>Git</contributor>
         <contributor>dependabot[bot]</contributor>
     </contributors>
     <categories>
         <category>maven-release</category>
         <category>bots</category>
      </categories>
</hide>
```
The config in its entirety is https://github.com/microsoft/gctoolkit/blob/2c90b363f66fa40aad14adef7fdb007437ab807c/pom.xml#L528

My command line is 
``` 
./mvnw -B -pl :gctoolkit -Pjreleaser jreleaser:release \
  -Djreleaser.previous.tag.name=gctoolkit-3.0.4 \
  -Djreleaser.tag.name=gctoolkit-3.0.5 \
  -Djreleaser.skip.release=true
```
This is using jreleaser:jreleaser-maven-plugin:1.15.0

**Reply by aalmiray** [reply]
Oh that's right. I'll run a check on a local repo. The git tags at the end of the commit message should have been picked up by the labeler as you expected.

**Comment by aalmiray** [comment, marked as answer]
The answer was staring right at me but I couldn't see it. What happens is that categories are sorted by key, which end up resolving as

```yaml
categories:
    category 0:
        key: ♻️  Changes
        title: ♻️  Changes
        labels:
            github-issue
    category 1:
        key: bots
        title: bots
        labels:
            bots
    category 2:
        key: maven-release
        title: maven-release
        labels:
            maven-release
```

This makes "♻️  Changes" be applied before "bots" which categorizes dependabot commits as changes instead. However, there's a workaround (and I believe this is why we added the following property): use the `order` property such as

```yaml
      categories:
        - title: bots
          order: 1
          labels:
            - bots
        - title: maven-release
          order: 2
          labels:
            - maven-release
        - title: ♻️  Changes
          order: 3
          labels:
            - github-issue
```

This resolves categories in the given order, giving "bots" priority over "changes"

```yaml
categories:
    category 0:
        key: bots
        title: bots
        labels:
            bots
        order: 1
    category 1:
        key: maven-release
        title: maven-release
        labels:
            maven-release
        order: 2
    category 2:
        key: ♻️  Changes
        title: ♻️  Changes
        labels:
            github-issue
        order: 3
```

Resulting in a changelog such as

## Changelog

## maven-release
- 74afc43 [maven-release-plugin] rollback changes from release preparation of my-branch (David Grieve)
- 2cd229a [maven-release-plugin] prepare branch @{releaseLabel} (David Grieve)
- e502037 [maven-release-plugin] prepare for next development iteration (GitHub Actions)

## ♻️  Changes
- 2f14bd6 Changes for publishing to Maven Central (#399) (David Grieve)
- 753d463 Update dependencies but disable rat plugin as mvnw won't pick up correct config (#390) (Martijn Verburg)
- aaeb875 Improve Archive Region Calculation (#211) (#369) (Danny Lau)
- 00ff2f8 Generational zgc (#368) (Kirk Pepperdine)
- 045a372 Dependencies and plugins updated to latest possible (#367) (Martijn Verburg)
- ff53a38 Add Evacuation workers getter for G1 GC (#366) (AlinaHovakimyan)
- 81b2744 Estimate the start time by variance (#360) (Danny Lau)
- 6eb4d71 Fix for gctoolkit #352 (Generational Heap Parser fails to recognize parallel gc lines) (#362) (jlittle-ptc)
- c0468f0 Update dependencies (#354) (Martijn Verburg)
- 64dd6dd PreUnified now works with DateStamps only (#347) (Kirk Pepperdine)
- 0dc33b9 Update to latest versions (#345) (Martijn Verburg)
- b55dafe I need a title (#344) (Kirk Pepperdine)
- b8f9f91 Collapse of CMSParser into GenerationHeapParser (#337) (Kirk Pepperdine)
- 1476fc1 Fix cms corner case (#332) (tiegen)
- 151b68b Issue 316 (#331) (Kirk Pepperdine)
- 26e08f2 Latest dependencies (#329) (Martijn Verburg)
- 4ece7df Mark ConcurrentModeFailure and ConcurrentModeInterrupted as CMSPhase (#326) (tiegen)
- 3cb229b Move g1 heapRegionSize from class variable to member variable (#324) (tiegen)
- 21c0d27 Catch IllegalArgumentException (#325) (Kirk Pepperdine)
- 394aa41 Correct CMSTenuredPoolParser (#320) (tiegen)
- 46e9d51 Fix YAML for ea workflow (#317) (Martijn Verburg)
- 7aecfbd Update dependencies and ability to pass in compile version (#314) (Martijn Verburg)
- 205ae89 Fill in region summaries for G1GCFull (#315) (tiegen)
- 4342691 First attempt at GH Action updates (#310) (Martijn Verburg)
- b286fcb Nov 2023 dep updates (#309) (Martijn Verburg)
- 8ca0d90 Support edan and survivor occupancy (#308) (tiegen)
- 4966123 Correct ZGCCycle gcType (#306) (tiegen)
- 2a57be7 More dependency updates (#303) (Martijn Verburg)
- 07194a2 Order keys by mru parse rule (#295) (David Grieve)
- f49a8f9 Update all deps, tests pass (#294) (Martijn Verburg)
- 7f43b59 update deps 8 may 2023 (#292) (Martijn Verburg)
- 92b07d9 Aggregator completion thread needs to be daemon (#291) (David Grieve)

---
- b9cac58 Fix indentation (David Grieve)
- 9e570a4 fix path on checkout (David Grieve)
- 55f0362 remove repository config (David Grieve)
- 2a3f172 trigger: none (David Grieve)
- 76d1fbe refactor: bump to JDK 17 (Kirk Pepperdine)
- 7b1218c fix potential substring(0,0) (David Grieve)
- f111734 additional minor optimization in UnifiedG1GCParser (David Grieve)


## Contributors
We'd like to thank the following people for their contributions:
Alina Hovakimyan, AlinaHovakimyan, Danny Lau, David Grieve, Derek Keeler, Joe Braley, Kirk Pepperdine, Luigi Montoya, Martijn Verburg, jlittle-ptc, loyispa, tiegen
