### DISCUSSION TITLE
Go docker packaging keeps failing

### DISCUSSION THREAD

**Discussion by gerardnico** [jreleaser/jreleaser#1834] [Q&A]
Hello,

I have made a fork of the go example and [added docker as packager](https://github.com/gerardnico/helloworld-go/commit/47ed50472013e7df69b8a14dfa597c3c1970fa70)

```yaml
packagers:
  docker:
    active: ALWAYS
    buildx:
      platforms:
        - 'linux-x86_64'
```

But the docker packaging keeps failing with
```bash
jreleaser assemble
jreleaser package --dry-run
```

```
[ERROR]     [docker] Dockerfile:13
[ERROR]     [docker] --------------------
[ERROR]     [docker]   11 |
[ERROR]     [docker]   12 |     COPY assembly/ /
[ERROR]     [docker]   13 | >>> RUN chmod +x helloworld-0.1.1-linux-arm64/bin/helloworld
[ERROR]     [docker]   14 |
[ERROR]     [docker]   15 |
[ERROR]     [docker] --------------------
[ERROR]     [docker] ERROR: failed to solve: process "/bin/sh -c chmod +x helloworld-0.1.1-linux-arm64/bin/helloworld" did not complete successfully: exit code: 1
```

The [Dockerfile.tpl](https://github.com/jreleaser/jreleaser/blob/v1.17.0/core/jreleaser-templates/src/main/resources/META-INF/jreleaser/templates/binary/docker/Dockerfile.tpl) uses a `helloworld-0.1.1-linux-arm64` as `distributionArtifactRootEntryName`
but in the file system, there is none

```bash
tree out/jreleaser/package/helloworld/docker/
```

```
out/jreleaser/package/helloworld/docker/
├── assembly
│   ├── bin
│   │   └── helloworld
│   └── LICENSE
├── Dockerfile
└── LICENSE
```

I tried the [multiple_dockerfile_per_distribution](https://jreleaser.org/guide/latest/reference/packagers/docker.html#_multiple_dockerfile_per_distribution) without any luck. 

Did I miss a configuration?

Thanks

Version:
```bash
jreleaser --version
```
```
------------------------------------------------------------
jreleaser 1.17.0
------------------------------------------------------------
Build time:   2025-02-28 07:33:53Z
Revision:     30d1905d021c89f769520d13b8d143918abec3ff
JVM:          21.0.5 (Azul Systems, Inc. 21.0.5+11-LTS)
------------------------------------------------------------
```

**Comment by gerardnico** [comment]
I'm fucking lost on how the docker workflow is working.

I created a [docker template](https://github.com/gerardnico/mail-checker/blob/main/.jreleaser/docker/Dockerfile.tpl) to solve the problem 
but now when I want to push the image,
```bash
jreleaser publish 
```
it just creates:
* a [dockerfile in the root](https://github.com/gerardnico/mail-checker/commit/7434a56511b87e48080f572ff550ca780338aa30) 
* add a [directory](https://github.com/gerardnico/mail-checker/tree/main/assembly)
* add a tag 
* and a commit!

Help... I'm completely lost
I'm going to use [ko](https://ko.build/) for the time being.

**Reply by gerardnico** [reply]
Pfff, the `repository` property of docker is to save the generate document it seems.

**Comment by gerardnico** [comment]
Another thing that I don't understand is how to filter by platform.
I have 3 platforms in the matrix and I want only one docker image for the platform says only linux-x86_64.
As of today, it will publish 3 docker images to the registry.

I tried:
```yaml
distributions:
  mail-checker:
    docker:
      specs:
        linux-amd:
          imageNames:
            - 'gerardnico/mail-checker:{{tagName}}'
          # match by platform
          matchers:
            platform: 'linux-x86_64'
```
does not work

I tried:
```yaml
packagers:
  docker:
    buildx:
       platforms:
        - 'linux-x86_64'
```
does not work.

With the `-g` option (debug), I don't get any extra-info on how I could filter them out or how they are chosen.
