### DISCUSSION TITLE
How to prevent nexus2 publishing from overwritting the maven-metadata.xml with only single version included?

### DISCUSSION THREAD

**Discussion by marko-bekhta** [jreleaser/jreleaser#1862] [Q&A]
Hey 👋🏻 ,

I've been playing around with JReleaser for Hibernate projects 😃 and noticed a problem with publishing snapshots through `nexus2` (OSSRH). 

The relative config part is:
```yaml
deploy:
  maven:
    nexus2:
      maven-central-snapshot:
        active: SNAPSHOT
        url: https://oss.sonatype.org/service/local
        snapshotUrl: https://oss.sonatype.org/content/repositories/snapshots/
        closeRepository: true
        releaseRepository: true
        javadocJar: false
        sign: false
        stagingRepositories:
          - target/staging-deploy/maven
```
JReleaser is executed in a standalone mode. Prior to that the `target/staging-deploy/maven` is populated by the build tool with all the required artifacts. 
Since publishing to a local directory means that the build tool also "downloads" the maven metadata from it, we end up with the XML containing just the version we are about to publish. And after the upload, all previously published versions disappear from the `maven-metadata`.  For example:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<metadata>
  <groupId>org.hibernate.infra</groupId>
  <artifactId>hibernate-asciidoctor-theme</artifactId>
  <versioning>
    <versions>
      <version>5.0.8-SNAPSHOT</version>
    </versions>
    <lastUpdated>20250428163345</lastUpdated>
  </versioning>
</metadata>
```

I noticed that there's this issue opened for the maven deploy plugin: https://github.com/apache/maven-deploy-plugin/issues/122, but even if that one is resolved there's going to be a similar issue with the gradle-based builds. 

Hence, a question ... did I miss something while configuring JReleaser, and can it currently handle this scenario? 
For the moment, I'm thinking about creating an extension that would download the metadata and merge it with the local file before the sign/upload steps.
