### DISCUSSION TITLE
Move release from OSSRH to Maven Central

### DISCUSSION THREAD

**Discussion by jonas-grgt** [jreleaser/jreleaser#1870] [Q&A] [answered]
I'm in the midst of moving a deployment from OSSRH to Maven Central as OSSRH is reaching end-of-life.

I've migrated my namespace to Maven Central and can see it when I login.

In the past I was using the `nexus2` deploy but for some reason this one always gives me unauthenticated.

I tried using the `mavenCentral` deployer yet then I'm hitting another error ` Caused by: org.jreleaser.model.spi.deploy.DeployException: Could not find a staging profile matching io.jonasg`

Is this the real cause or might it be because there is something of with my credentials?

Can I still use the `nexus2` deployer when deploying to Maven Central?
Do I need to change the URL from to `https://central.sonatype.com/api/v1/publisher`?

Extract of my `pom.xml`
```
<deploy>
	<maven>
		<nexus2>
			<app>
				<active>ALWAYS</active>
				<url>https://central.sonatype.com/api/v1/publisher</url>
				<closeRepository>true</closeRepository>
				<releaseRepository>false</releaseRepository>
				<stagingRepositories>target/staging-deploy</stagingRepositories>
			</app>
		</nexus2>
	</maven>
</deploy>
```

Extract from my github actions file.
Not sure if I'm using the correct environment variables for authentication.
```
    - name: Release
      env:
        JRELEASER_NEXUS2_USERNAME: ${{ secrets.JRELEASER_NEXUS2_USERNAME }}
        JRELEASER_NEXUS2_PASSWORD: ${{ secrets.JRELEASER_NEXUS2_PASSWORD }}
        JRELEASER_GPG_PASSPHRASE: ${{ secrets.JRELEASER_GPG_PASSPHRASE }}
        JRELEASER_GPG_SECRET_KEY: ${{ secrets.JRELEASER_GPG_SECRET_KEY }}
        JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.JRELEASER_GPG_PUBLIC_KEY }}
        JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./mvnw -Prelease jreleaser:full-release --non-recursive -X
```

Any kind of help is more then appreciated!
