### DISCUSSION TITLE
Announce/notify to multiple Slack Channels

### DISCUSSION THREAD

**Discussion by dhrudevalia** [jreleaser/jreleaser#1886] [Ideas]
## Feature Request
While implementing the announcement for one our projects we encountered a gap which is to be able to publish the Slack announcement to multiple Slack channels.

Ideally this could look something like:

```
announce:
  slack:
    active: ALWAYS
    channel: 
      - #global-release
      - #connector-release
```
Or equivalent.
