### DISCUSSION TITLE
Changelog content

### DISCUSSION THREAD

**Discussion by ayechantharsoe** [jreleaser/jreleaser#261] [Q&A]
For GitHub release, Can we include only the titles of issues&pr in changelog?
I am asking because PR created using @dependabot contains so many comment that the changelog become full of unrelated contents.

And also a PR which contains many commits also bloat the changelog.

**Comment by aalmiray** [comment]
Yes, you can activate changelog formatting as shown at https://jreleaser.org/guide/latest/examples/jreleaser.html

**Reply by ayechantharsoe** [reply]
![image](https://user-images.githubusercontent.com/8254188/124409636-b489c180-dd6e-11eb-9b05-ee21618ae31b.png)

Ok first I thought replacers will help but it is replacing only the matched word.
What I want to do is, 

if the PR title starts with `^Bump` then don't include the commit message which is following.

```
Bumps [flyway-core](https://github.com/flyway/flyway) from 7.9.2 to 7.11.0.
- [Release notes](https://github.com/flyway/flyway/releases)
- [Commits](https://github.com/flyway/flyway/compare/flyway-7.9.2...flyway-7.11.0)

---
updated-dependencies:
- dependency-name: org.flywaydb:flyway-core
  dependency-type: direct:production
  update-type: version-update:semver-minor
...

Signed-off-by: dependabot[bot] <support@github.com> (dependabot[bot])
```

Is this possible?
