### DISCUSSION TITLE
Suddenly my CLI is packaged as a Cask instead of a Tap

### DISCUSSION THREAD

**Discussion by helpermethod** [jreleaser/jreleaser#334] [Q&A] [answered]
Up until the latest release, `connect-offset-reset` was correctly packaged as a Brew Tap, which is as expected.

https://github.com/helpermethod/homebrew-tap/blob/master/Formula/connect-offset-reset.rb

But after upgrading to the lastest stable JReleaser version it got packaged as a Brew Cask (which for a CLI app doesn't seem right).

https://github.com/helpermethod/homebrew-tap/tree/master/Casks

I didn't change anything in the `jreleaser.yml`
https://github.com/helpermethod/connect-offset-reset/blob/main/jreleaser.yml

Greets, and keep up the great work!

**Comment by aalmiray** [comment]
Oops, I think this is an aggressive configuration when a `.zip` file is detected. Please set `brew.cask.enabled: false` as a workaround.

**Comment by aalmiray** [comment, marked as answer]
Looks like the combination of `distribution.type` and `artifact.platform` triggers the choice between formula and cask.

```yml
packagers:
  brew:
    active: always

distributions:
  app:
    type: JAVA_BINARY
    artifacts:
      - path: target/distributions/{{distributionName}}/{{distributionName}}-{{projectVersion}}.zip
```

Results on the following resolved model

```yml
distributions:
    app:
        enabled: true
        active: always
        type: JAVA_BINARY
        executable: app
        artifacts:
            artifact 0:
                path: target/distributions/app/app-1.0.0.zip
        java:
            enabled: true
            version: 8
            groupId: com.acme
            artifactId: app
            multiProject: false
        brew:
            enabled: true
            active: always
            continueOnError: false
            templateDirectory: src/jreleaser/distributions/app/brew
            commitAuthor:
                name: jreleaserbot
                email: jreleaser@kordamp.org
            formulaName: app
            multiPlatform: false
            tap:
                owner: aalmiray
                name: homebrew-tap
                branch: HEAD
                username: aalmiray
                token: ************
            cask:
                enabled: false
```

Here the formula is available while the cask is disabled. Running `jreleaser prepare` yields

```
out/jreleaser/prepare/
└── app
    └── brew
        ├── Formula
        │   └── app.rb
        ├── LICENSE
        └── README.md
```

Now, adding a value for the artifact's platform such as

```yml
packagers:
  brew:
    active: always

distributions:
  app:
    type: JAVA_BINARY
    artifacts:
      - path: target/distributions/{{distributionName}}/{{distributionName}}-{{projectVersion}}.zip
        platform: osx-x86_64
```

Results in the following resolved model

```yml
distributions:
    app:
        enabled: true
        active: always
        type: JAVA_BINARY
        executable: app
        artifacts:
            artifact 0:
                path: target/distributions/app/app-1.0.0.zip
                platform: osx-x86_64
        java:
            enabled: true
            version: 8
            groupId: com.acme
            artifactId: app
            multiProject: false
        brew:
            enabled: true
            active: always
            continueOnError: false
            templateDirectory: src/jreleaser/distributions/app/brew
            commitAuthor:
                name: jreleaserbot
                email: jreleaser@kordamp.org
            formulaName: app
            multiPlatform: false
            tap:
                owner: aalmiray
                name: homebrew-tap
                branch: HEAD
                username: aalmiray
                token: ************
            cask:
                enabled: true
                name: app
                displayName: App
```

Where both formula and cask appear enabled, however the cask wins, which results in a generated cask after invoking `jreleaser prepare`

```
out/jreleaser/prepare/
└── app
    └── brew
        ├── Casks
        │   └── app.rb
        ├── LICENSE
        └── README.md
```

Now, switching the distribution type from `JAVA_BINARY` to `BINARY` requires every artifact in the distribution to define a platform value, which we know will force a cask instead of a formula. A validation error occurs if no platform is defined, such as

```yml
packagers:
  brew:
    active: always

distributions:
  app:
    type: BINARY
    artifacts:
      - path: target/distributions/{{distributionName}}/{{distributionName}}-{{projectVersion}}.zip
```

Results in

```
[WARN]    [validation] disabling distribution.app.brew because there are no matching artifacts
[ERROR] == JReleaser ==
[ERROR] distribution.app is of type BINARY and brew requires a explicit platform on each artifact
JReleaser has not been properly configured.
```

I'm afraid that my previous suggestion to disable the cask explicitly won't work either, as witnessed by

```yml
packagers:
  brew:
    active: always
    cask:
      enabled: false

distributions:
  app:
    type: BINARY
    artifacts:
      - path: target/distributions/{{distributionName}}/{{distributionName}}-{{projectVersion}}.zip
        platform: osx-x86_64
```

Resulting in the following resolved model

```yml
distributions:
    app:
        enabled: true
        active: always
        type: BINARY
        executable: app
        artifacts:
            artifact 0:
                path: target/distributions/app/app-1.0.0.zip
                platform: osx-x86_64
        brew:
            enabled: true
            active: always
            continueOnError: false
            templateDirectory: src/jreleaser/distributions/app/brew
            commitAuthor:
                name: jreleaserbot
                email: jreleaser@kordamp.org
            formulaName: app
            multiPlatform: false
            tap:
                owner: aalmiray
                name: homebrew-tap
                branch: HEAD
                username: aalmiray
                token: ************
            cask:
                enabled: true
                name: app
                displayName: App
```

This is indeed a bug introduced by `v0.6.0`. But not the one I thought. Setting up brew at the distribution level shows a different picture

```yml
distributions:
  app:
    type: BINARY
    brew:
      active: always
      cask:
        enabled: false
    artifacts:
      - path: target/distributions/{{distributionName}}/{{distributionName}}-{{projectVersion}}.zip
        platform: osx-x86_64
```

Results in

```yml
distributions:
    app:
        enabled: true
        active: always
        type: BINARY
        executable: app
        artifacts:
            artifact 0:
                path: target/distributions/app/app-1.0.0.zip
                platform: osx-x86_64
        brew:
            enabled: true
            active: always
            continueOnError: false
            templateDirectory: src/jreleaser/distributions/app/brew
            commitAuthor:
                name: jreleaserbot
                email: jreleaser@kordamp.org
            formulaName: app
            multiPlatform: false
            tap:
                owner: aalmiray
                name: homebrew-tap
                branch: HEAD
                username: aalmiray
                token: ************
            cask:
                enabled: false
```

So there's indeed a bug but it's originated when copying global packagers settings into local distribution packager settings. The workaround does yield the expected result but you must use a local packager instead of a global one.
