### DISCUSSION TITLE
Tip: Inspect the JReleaser out/ directory with GitHub Actions

### DISCUSSION THREAD

**Discussion by sualeh** [jreleaser/jreleaser#697] [Ideas]
Once you have got your JReleaser configuration working locally, you may want to inspect what is created in production. If you use GitHub Actions, add an additional step after the JReleaser action, like the one below. It will allow you to download the contents of the out directory after the GitHub Actions workflow finishes. 

```yaml
    - id: persist-jreleaser-out
      name: Persist JReleaser out/ directory
      uses: actions/upload-artifact@v2
      with:
        name: jreleaser-out
        path: |
          ./out/
        retention-days: 1
```

This can be combined with debug logs from JReleaser for even more information, if you add a `-g` flag to JReleaser, as shown below:

```yaml
    - id: jreleaser
      name: Run JReleaser
      uses: jreleaser/release-action@v1
      env:
        JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        arguments: "full-release -g"
```
