### DISCUSSION TITLE
How to include platform replacements in the fileSets input?

### DISCUSSION THREAD

**Discussion by manojkarthick** [jreleaser/jreleaser#700] [Q&A] [answered]
I'm trying to experiment with JReleaser for my rust project and would appreciate some help with figuring out how to include platform replacements.

I followed the blog post at https://andresalmiray.com/releasing-rust-binaries-with-jreleaser/ to create a hello world rust project to use JReleaser with Github Actions.

Currently Github does not provide VMs with aarch64 macOS, so instead I'm trying to use the x64 macOS VM to cross-compile the binaries. 

I have a platform replacements section like:
```
platform:
  replacements:
    'osx-x86_64': 'x86_64-apple-darwin'
    'osx-aarch_64': 'aarch64-apple-darwin'
    'linux-x86_64': 'x86_64-unknown-linux-gnu'
    'windows-x86_64': 'x86_64-pc-windows-msvc'
```

When a target is specified using `--target`, rust build the binaries to target/<target_name>/release/` rather than at `target/release`. So I'd like to update my assemble section to include the platform replacement, but I am not sure if that is supported.

So, instead of this:
```
assemble:
  archive:
    jreleaser-poc:
      active: ALWAYS
      formats: [ ZIP ]
      attachPlatform: true
      fileSets:
        - input: 'target/release'
          output: 'bin'
          includes: [ 'jreleaser-poc{.exe,}' ]
        - input: '.'
          includes: [ 'LICENSE' ]
```

I want something like this (with the updated release path):
```
assemble:
  archive:
    jreleaser-poc:
      active: ALWAYS
      formats: [ ZIP ]
      attachPlatform: true
      fileSets:
        - input: 'target/{{ platformReplacement }}/release'
          output: 'bin'
          includes: [ 'jreleaser-poc{.exe,}' ]
        - input: '.'
          includes: [ 'LICENSE' ]
```

I'm still exploring the project, so apologies if I might've missed an obvious way to do this.

**Comment by aalmiray** [comment, marked as answer]
It is possible if you use `{{ osPlatformReplaced }}`. Available name templates are shown at https://jreleaser.org/guide/latest/configuration/name-templates.html

**Reply by manojkarthick** [reply]
Thank you so much!

**Reply by manojkarthick** [reply]
Sorry to reopen this thread: since multiple binaries are built on the same platform, eg. both aarch64 and x86_64 binaries for macOS on built on x86_64, the `{{ osPlatformReplaced }}` doesn't seem to do the job. Both builds use the `x86_64-apple-darwin` replacement. I tried passing the `RUSTUP_TARGET` as an environment variable to the github action and then referenced in the jreleaser.yml file. But looks like the step's environment variable doesn't get rendered by JReleaser.

Sample:
- jreleaser config: https://github.com/manojkarthick/jreleaser-poc/blob/master/jreleaser.yml
- actions workflow: https://github.com/manojkarthick/jreleaser-poc/blob/master/.github/workflows/early-access.yml

Output snippet from `trace.log`:
```
assemble:
    enabled: true
    archive:
        jreleaser-poc:
            enabled: true
            exported: true
            active: always
            platform:
            archiveName: {{distributionName}}-{{projectVersion}}
            distributionType: BINARY
            attachPlatform: true
            formats:
                zip
            fileSets:
                fileSet 0:
                    input: target/{{Env.RUSTUP_TARGET}}/release
                    output: bin
                    includes:
                        jreleaser-poc{.exe,}
                fileSet 1:
                    input: .
                    includes:
                        LICENSE
```

 Looks like passing env vars like this is not supported (from what I read on the jreleaser/release-action [docs](https://github.com/jreleaser/release-action#environment-variables)). Is my understanding correct?
