### DISCUSSION TITLE
How to configure assemble format based on platform

### DISCUSSION THREAD

**Discussion by manojkarthick** [jreleaser/jreleaser#701] [Q&A] [answered]
In this assemble section in `jreleaser.yml`, I see that we can configure multiple archive formats using something like:
```
assemble:
  archive:
    jreleaser-poc:
      active: ALWAYS
      formats: [ TAR_GZ, ZIP ]
      attachPlatform: true
```

but is it possible to configure this based on the platform is it assembling for? I'd like to use `.zip` for windows but `.tar.gz` for *nix.
