### DISCUSSION TITLE
brew name, scoop name and fish name are not set correctly

### DISCUSSION THREAD

**Discussion by ahmedsaheed** [jreleaser/jreleaser#852] [Q&A]
Hello Again,

I was wondering why whenever i run `./gradlew jreleaserConfig` my `tapName = ahmedsaheed` whereas in my build.gradle file i have set it to `homebrew-tap`

This same scenario occurs with both scoop and fish

Meaning, when i run `./gradlew jreleaserFullRelease` i get an error because they both try to create a repo with `ahmedsaheed/ahmedsaheed` instead of `ahmedsaheed/homebrew-tap` or `ahmedsaheed/scoop-ahmedsaheed`
```
-  [brew] setting up repository ahmedsaheed/ahmedsaheed
-  [scoop] setting up repository ahmedsaheed/ahmedsaheed
```

**Comment by aalmiray** [comment]
FWIW the GoFish packager has been abandoned by its author. I'd recommend skipping it.
Could you post the evaluated section for the configured distribution when running `gradle jreleaserConfig` ?

**Comment by ahmedsaheed** [comment]
On further search i found out the packager has been abandoned.

Here is what i have in my build.gradle

```groovy
packagers {
        brew {
            active = 'ALWAYS'
            continueOnError = false
            downloadUrl = 'https://{{repoHost}}/{{repoOwner}}/{{repoName}}/releases/download/{{tagName}}/{{artifactFile}}'
            commitAuthor {
                name = 'Ahmed Saheed'
                email = 'saheed@quranCLI.com'
            }
            repoTap {
                active = 'ALWAYS'
                owner = 'ahmedsaheed'
                name = 'homebrew-tap'
                tagName = '{{distributionName}} {{tagName}}'
                branch = 'HEAD'
                username = 'ahmedsaheed'
                commitMessage = '{{distributionName}} {{tagName}}'
            }
            formulaName = 'qurancli'
            multiPlatform = true
        }

        scoop {
            active = 'ALWAYS'
            continueOnError = false
            downloadUrl = 'https://{{repoHost}}/{{repoOwner}}/{{repoName}}/releases/download/{{tagName}}/{{artifactFile}}'
            commitAuthor {
                name = 'Ahmed Saheed'
                email = 'saheed@quranCLI.com'
            }
            bucket{
                active = 'ALWAYS'
                owner = 'ahmedsaheed'
                name = 'scoop-ahmedsaheed'
                tagName = '{{distributionName}} {{tagName}}'
                branch = 'HEAD'
                username = 'ahmedsaheed'
                commitMessage = '{{distributionName}} {{tagName}}'
            }
        }

    }
```

And here is what was evaluated on running `gradle jreleaserConfig`


```
packagers:
    brew:
        enabled: true
        active: always
        continueOnError: false
        downloadUrl: https://{{repoHost}}/{{repoOwner}}/{{repoName}}/releases/download/{{tagName}}/{{artifactFile}}
        commitAuthor:
            name: Ahmed Saheed
            email: saheed@quranCLI.com
        formulaName: qurancli
        multiPlatform: true
        tap:
            enabled: true
            active: always
            owner: ahmedsaheed
            name: ahmedsaheed
            tagName: {{distributionName}} {{tagName}}
            branch: HEAD
            username: ahmedsaheed
            token: ************
            commitMessage: {{distributionName}} {{tagName}}
        cask:
            enabled: false
    scoop:
        enabled: true
        active: always
        continueOnError: false
        downloadUrl: https://{{repoHost}}/{{repoOwner}}/{{repoName}}/releases/download/{{tagName}}/{{artifactFile}}
        commitAuthor:
            name: Ahmed Saheed
            email: saheed@quranCLI.com
        bucket:
            enabled: true
            active: always
            owner: ahmedsaheed
            name: ahmedsaheed
            tagName: {{distributionName}} {{tagName}}
            branch: HEAD
            username: ahmedsaheed
            token: ************
            commitMessage: {{distributionName}} {{tagName}}

```

Also when i comment out both tap and bucket name, it doesn't set to default
