### DISCUSSION TITLE
Possible to also update changelog content into file?

### DISCUSSION THREAD

**Discussion by nazeem-soeltan-maersk** [jreleaser/jreleaser#947] [Q&A] [answered]
Hi,

Currently the changelog contents are being put under the Deployments > Releases tab of gitlab.
Is it possible that the changelog changes are also added / appended into a file CHANGELOG.md in the root of the project's directory? Thus, CHANGELOG.md always containing the full history of releases / commits.

Currently the changelog config looks like this.

```
release:
  gitlab:
    changelog:
      enabled: true
      sort: DESC
      formatted: ALWAYS
      preset: conventional-commits
      format: '- {{commitShortHash}} {{commitTitle}}'
      content: |
        # {{projectName}} changelog
        ## {{tagName}}
        {{changelogChanges}}
        {{changelogContributors}}
```
