### ISSUE TITLE
[init] Generated jreleaser file does not have a resolved timestamp

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#1023]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem (link to git repository is ideal)
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Invoke `jreleaser init -f yml`

### Expected Behaviour

The generated file should have a creation timestamp at the top

### Actual Behaviour

The file has a placeholder for the timestamp instead.

```yaml
# {{jreleaserCreationStamp}}
project:
  name: app
  version: 1.0.0-SNAPSHOT
  description: Awesome App
  ...
```

### Environment Information

- **Operating System**: N/A
- **JReleaser Version:** 1.3.1
- **JDK Version:** N/A
