### ISSUE TITLE
[assemble] Migrate executable property to typed section

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#1029]
Affects `jlink`, `jpackage`, and `nativeImage`.

The `executable` property ( as of `1.x` it's of type  `String`) should become a typed section such as:

```yml
executable:
  name: 'app'
  unixExtension: 'sh'
  windowsExtension: 'cmd'
```
