### ISSUE TITLE
[deploy] Let pomchecker version be configurable

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#1157]
JReleaser relies in [pomchecker](https://github.com/kordamp/pomchecker) to verify POMs may be published to Maven Central. Currently it internally defines which version of pomchecker may be used. This version should be configurable.

Proposed DSL change:

```yaml
deploy:
  maven:
    pomchecker:
      version: x.y.z
```
