### ISSUE TITLE
Support GitHub Action running with JReleaser snapshot version

### ISSUE THREAD

**Issue by dmurat** [jreleaser/jreleaser#120]
**Is your feature request related to a problem? Please describe.**
I cannot run the JReleaser GitHub action with the snapshot version of JReleaser.

**Describe the solution you'd like**
I will like to be able to run the GitHub workflow with JReleaser's snapshot version.

**Additional context**
I configured JReleaser GitHub action with `0.3.0-SNAPSHOT` version:
```
      - name: Run JReleaser
        uses: jreleaser/release-action@v1
        with:
          version: 0.3.0-SNAPSHOT
          arguments: changelog --basedir=${{ github.workspace }} --config-file=${{ github.workspace }}/support/jreleaser/jreleaser-${{ github.event.inputs.release-type }}.yml
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JRELEASER_PROJECT_VERSION: ${{ github.event.inputs.release-version }}

      - name: JReleaser output
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: JReleaser logs
          path: |
            out/jreleaser/trace.log
            out/jreleaser/output.properties
            out/jreleaser/release/CHANGELOG.md
```
Unfortunately, action reported that it cannot find the 0.3.0-SNAPSHOT version:

```
Run jreleaser/release-action@v1
  with:
    version: 0.3.0-SNAPSHOT
    arguments: changelog --basedir=/home/runner/work/klokwrk-project/klokwrk-project --config-file=/home/runner/work/klokwrk-project/klokwrk-project/support/jreleaser/jreleaser-draft.yml
    working-directory: /home/runner/work/klokwrk-project/klokwrk-project
  env:
    JAVA_HOME_11.0.11_x64: /opt/hostedtoolcache/jdk/11.0.11/x64
    JAVA_HOME: /opt/hostedtoolcache/jdk/11.0.11/x64
    JAVA_HOME_11_0_11_X64: /opt/hostedtoolcache/jdk/11.0.11/x64
    JRELEASER_GITHUB_TOKEN: ***
    JRELEASER_PROJECT_VERSION: 0.0.5-SNAPSHOT
📦 Download JReleaser
  ❌ JReleaser 0.3.0-SNAPSHOT not found
  Error: Process completed with exit code 1.
```

Please, don't mind this feature request if it is too complicated to implement.
