### ISSUE TITLE
[core] Let command hooks be filtered by platform

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#1208]
Command hooks execute a system command. There may be times where the command is not available on a given platform. Add an option to define which platforms mark the hook for inclusion/exclusion such that

Excludes the hook from Windows

```yaml
hooks:
  command:
    success:
      - cmd: 'echo {{event.name}} {{event.type}}'
        platforms:
          - '!windows'
```

Includes the hook only for Linux

```yaml
hooks:
  command:
    success:
      - cmd: 'echo {{event.name}} {{event.type}}'
        platforms:
          - linux
```
