### ISSUE TITLE
[changelog] Add commitsUrl in the context of changelog.change template

### ISSUE THREAD

**Issue by dmurat** [jreleaser/jreleaser#121]
**Is your feature request related to a problem? Please describe.**
When generating a changelog for GitHub, I will like to apply code formatting on commit short hash. Something like this example:

[`33a52c2`](https://github.com/croz-ltd/klokwrk-project/commits/33a52c2) feat(project): Add changelog generator for JReleaser "draft" release

For this purpose, I tried to use the following changelog change template:

```
release:
  github:
    changelog:
      enabled: true
      formatted: ALWAYS
      change: "- [`{{commitShortHash}}`]({{commitsUrl}}/{{commitShortHash}}) {{commitTitle}}"
      links: false
```

Unfortunately, `commitsUrl` is not available in the template context.

**Describe the solution you'd like**
I will like that `commitsUrl` is included in the template context, if possible:
https://github.com/jreleaser/jreleaser/blob/3154bf918d26ab8e3de40fb8b5d059e84c9a1f2f/sdks/git-sdk/src/main/java/org/jreleaser/sdk/git/ChangelogGenerator.java#L345

**Describe alternatives you've considered**
A workaround is to use hardcoded expanded commits URL:

```
change: "- [`{{commitShortHash}}`](https://github.com/croz-ltd/klokwrk-project/commits/{{commitShortHash}}) {{commitTitle}}"
```

It is not really a problem but makes the JReleaser config less portable between projects, and, if possible, I will like to avoid this.

Tnx
