### ISSUE TITLE
[assemble] Jdeps targets should be resolved to absolute paths

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#1227]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem (link to git repository is ideal)
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Configure the JReleaser project with
```
assemble:
  jlink:
    jreleaser-standalone:
      active: ALWAYS
      java:
        version: 11
      imageName: '{{distributionName}}-{{projectEffectiveVersion}}'
      executable: jreleaser
      jdeps:
        multiRelease: base
        ignoreMissingDeps: true
        targets:
          - 'plugins/jreleaser/build/libs/jreleaser-{{projectVersion}}.jar'
```
2. Execute `jreleaser assemble`

### Expected Behaviour

Successful jlink images generated.

### Actual Behaviour

Failure such as

```
[ERROR]     [jlink] Error: Module Warning: Path does not exist: plugins/jreleaser/build/libs/jreleaser-1.6.0-SNAPSHOT.jar not found
java.lang.module.FindException: Module Warning: Path does not exist: plugins/jreleaser/build/libs/jreleaser-1.6.0-SNAPSHOT.jar not found
```

### Environment Information

- **Operating System**: TODO
- **JReleaser Version:** 1.6.0-SNAPSHOT
- **JDK Version:** TODO
