### ISSUE TITLE
[assemble] java-archive ignores executable.unixExtension

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#1248]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem (link to git repository is ideal)
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. `git clone https://github.com/jreleaser/helloworld-java-bin.git`
2. Modify assembler configuration to look like this
```
assemble:
  javaArchive:
    helloworld:
      active: ALWAYS
      formats: [ ZIP ]
      executable:
        unixExtension: sh
      fileSets:
        - input: '.'
          includes: [ 'LICENSE' ]
      mainJar:
        path: target/{{distributionName}}-{{projectVersion}}.jar
```
3. `jreleaser assemble`

### Expected Behaviour

Archive should contain `bin/helloworld.sh` 

### Actual Behaviour

Archive contains `bin/helloworld` 

### Environment Information

- **Operating System**: N/A
- **JReleaser Version:** 1.5.0
- **JDK Version:** N/A

cc: @bmarwell
