### ISSUE TITLE
[assemble] java-archive ignores java.mainModule

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#1249]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem (link to git repository is ideal)
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. `git clone https://github.com/jreleaser/helloworld-java-bin.git`
2. Modify project configuration to look like this
```
  java:
    groupId: org.jreleaser.examples
    artifactId: helloworld
    mainClass: org.jreleaser.examples.HelloWorld
    mainModule: org.jreleaser
```
3. `jreleaser assemble`

### Expected Behaviour

Generated launcher should configure execution with the modulepath

### Actual Behaviour

Classpath is used instead

### Environment Information

- **Operating System**: N/A
- **JReleaser Version:** 1.5.0
- **JDK Version:** N/A

cc: @bmarwell
