### ISSUE TITLE
[assemble] java-archive generates JAVA_OPTS with wrong format

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#1251]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem (link to git repository is ideal)
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. `git clone https://github.com/jreleaser/helloworld-java-bin.git`
2. Modify assembler configuration to look like this
```
assemble:
  javaArchive:
    helloworld:
      active: ALWAYS
      formats: [ ZIP ]
      fileSets:
        - input: '.'
          includes: [ 'LICENSE' ]
      mainJar:
        path: target/{{distributionName}}-{{projectVersion}}.jar
      java:
        options:
          - -Dfoo=foo
          - -Dbar=bar
```
3. `jreleaser assemble`

### Expected Behaviour

Generated launcher should contain
```
 JAVA_OPTS="-Dfoo=foo -Dbar=bar"
```

### Actual Behaviour

Generated launches contains
```
JAVA_OPTS="[-Dfoo&#61;foo, -Dbar&#61;bar]"
```

### Environment Information

- **Operating System**: N/A
- **JReleaser Version:** 1.5.0
- **JDK Version:** N/A

cc: @bmarwell
