### ISSUE TITLE
[packagers] Add option to skip copying LICENSE file to tap repository

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#1255]
Packagers that publish artifacts to a tap/repository automatically copy the `LICENSE` file if it exists. There may be times when this is not desirable such as pushing a delta to an existing repository like `macports/ports` or `microsoft/winget-pkgs`.

Packagers should add a `skipLicenseFile` extra property, for example:

```yaml
packagers:
  winget:
    active: RELEASE
    extraProperties:
      skipLicenseFile: true
    repository:
      owner: microsoft
      name: winget-pkgs
      branch: master
      branchPush: '{{projectName}}-{{tagName}}'
      message: '{{projectNameCapitalized}} version {{projectVersion}}'
```
