### ISSUE TITLE
[packagers] Default docker registry is missing repository name

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#1261]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem (link to git repository is ideal)
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Clone https://github.com/jreleaser/helloworld-java-jar
2. Update the distribution with a docker packager
```
distributions:
  helloworld:
    type: SINGLE_JAR
    artifacts:
      - path: target/{{distributionName}}-{{projectVersion}}.jar
    docker:
      active: ALWAYS
```
3. Build with `./mvnw verify`
4. Display the configuration with `jreleaser config`

### Expected Behaviour

The following configuration should be present
```
            registries:
                registry 0:
                    server: docker.io
                    serverName: docker.io
                    repositoryName: jreleaser
                    username: jreleaser
                    password: **unset**
                    externalLogin: false
```

### Actual Behaviour

`repositoryName` is missing

### Environment Information

- **Operating System**: N/A
- **JReleaser Version:** 1.5.0
- **JDK Version:** N/A
