### ISSUE TITLE
[assembler] NativeImage assembler cannot build executables using Java modules

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#1262]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem (link to git repository is ideal)
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Clone https://github.com/jreleaser/helloworld-java-graalvm
2. Update the java section as follows
```
  java:
    version: 17
    groupId: org.jreleaser.examples
    artifactId: helloworld
    mainClass: org.jreleaser.examples.HelloWorld
    mainModule: org.jreleaser.examples
```
3. Assemble the distribution

### Expected Behaviour

The binary should be built using modules as shown at https://www.graalvm.org/latest/reference-manual/native-image/guides/build-java-modules-into-native-executable/

### Actual Behaviour

The binary is built using the classpath

### Environment Information

- **Operating System**: N/A
- **JReleaser Version:** 1.5.0
- **JDK Version:** N/A
