### ISSUE TITLE
[core] Enum values are printed in lowercase which is confusing

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#1263]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem (link to git repository is ideal)
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. git clone https://github.com/jreleaser/helloworld-java-bin
2. Execute `jreleaser config`

### Expected Behaviour

`assemble` section should look like this
```
assemble:
    enabled: true
    active: ALWAYS
    javaArchive:
        helloworld:
            enabled: true
            exported: true
            active: ALWAYS
            stereotype: CLI
            archiveName: {{distributionName}}-{{projectVersion}}
            formats:
                ZIP
            executable:
                name: helloworld
                windowsExtension: bat
            mainJar:
                path: target/{{distributionName}}-{{projectVersion}}.jar
            java:
                mainClass: org.jreleaser.examples.HelloWorld
            templateDirectory: src/jreleaser/assemblers/helloworld/java-archive
            fileSets:
                fileSet 0:
                    input: .
                    includes:
                        LICENSE
```

### Actual Behaviour

`assemble` section looks like this instead
```
assemble:
    enabled: true
    active: always
    javaArchive:
        helloworld:
            enabled: true
            exported: true
            active: always
            stereotype: cli
            archiveName: {{distributionName}}-{{projectVersion}}
            formats:
                zip
            executable:
                name: helloworld
                windowsExtension: bat
            mainJar:
                path: target/{{distributionName}}-{{projectVersion}}.jar
            templateDirectory: src/jreleaser/assemblers/helloworld/java-archive
            fileSets:
                fileSet 0:
                    input: .
                    includes:
                        LICENSE
```

### Environment Information

- **Operating System**: N/A
- **JReleaser Version:** 1.5.0
- **JDK Version:** N/A
