### ISSUE TITLE
[releease] GitLab links non existent release assets

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#1272]
### Task List

- [x] Steps to reproduce provided
- [] Stacktrace (if present) provided
- [ ] Example that reproduces the problem (link to git repository is ideal)
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Configure a distribution with a single artifact
2. Disable files and artifacts from releases
3. Configure an S3 uploader
4. Perform a release

### Expected Behaviour

No assets uploaded except for checksums

### Actual Behaviour

GitLab attempts to link non existing distribution artifact

### Environment Information

- **Operating System**: N/A
- **JReleaser Version:** 1.5.0
- **JDK Version:** N/A

See https://gitlab.com/taxi-lang/taxi-lang/-/blob/develop/taxi-cli/jreleaser.yml

```
release:
   gitlab:
      owner: taxi-lang
      name: taxi-lang
      username: martypitt
      branch: master
      identifier: 3493030
      overwrite: true
      # Uploading files to gitlab is failing.
      # Grab them from the s3 repo instead
      files: false
      artifacts: false
      uploadLinks:
         s3: taxi

distributions:
   taxi:
      java:
         mainClass: lang.taxi.cli.TaxiCli
      executable:
         name: taxi/bin/taxi
      artifacts:
         - path: target/taxi.zip

upload:
   s3:
      taxi:
         active: ALWAYS
         region: eu-west-1
         bucket: repo.orbitalhq.com
         path: release/org/taxilang/taxi-cli/{{projectVersion}}/{{artifactFile}}
         downloadUrl: https://repo.orbitalhq.com/release/org/taxilang/taxi-cli/{{projectVersion}}/{{artifactFile}}
```

https://gitlab.com/taxi-lang/taxi-lang/-/jobs/3902018223 log contains the following

```
14079 [DEBUG] creating release on taxi-lang/taxi-lang with tag v1.36.0
14505 [DEBUG] uploading assets to taxi-lang/taxi-lang
14505 [INFO]  - uploading checksums_sha256.txt
15466 [INFO] linking assets to taxi-lang/taxi-lang with tag v1.36.0
15466 [INFO]  - linking checksums_sha256.txt
15732 [INFO] linking assets to taxi-lang/taxi-lang with tag v1.36.0
15732 [INFO]  - linking taxi.zip
```
