### ISSUE TITLE
[docker] Support multiple Docker configurations per distribution

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#129]
A distribution may have more than one artifact that may be packaged with Docker. Such artifacts should be handled separately.

The current workaround is to register multiple distributions but this posses a problem when artifacts come from an assembled distribution. Case in point: distributing cross-platform Java Runtimes where both `linux` and `linux_musl` platforms are configured.

Depends on #127, #128

**Comment by aalmiray** [comment]
Current spec looks like

```yaml

assemble:
  jlinks:
    jreleaser-standalone:
      active: always
      extraProperties:
        sdkmanSkip: true
      java:
        version: 11
        mainClass: org.jreleaser.cli.Main
      imageName: 'jreleaser-standalone-{{projectEffectiveVersion}}'
      executable: 'jreleaser'
      moduleNames:
        - java.base
        - java.desktop
        - java.management
        - java.naming
        - java.rmi
        - java.security.jgss
        - java.sql
      targetJdks:
        - path: 'apps/jreleaser/build/jdks/zulu11.48.21-ca-jdk11.0.11-macosx_x64/zulu-11.jdk/Contents/Home'
          platform: osx
        - path: 'apps/jreleaser/build/jdks/zulu11.48.21-ca-jdk11.0.11-linux_x64'
          platform: linux
        - path: 'apps/jreleaser/build/jdks/zulu11.48.21-ca-jdk11.0.11-linux_musl_x64'
          platform: linux_musl
        - path: 'apps/jreleaser/build/jdks/zulu11.48.21-ca-jdk11.0.11-win_x64'
          platform: windows
      mainJar:
        path: 'apps/jreleaser/build/libs/jreleaser-{{projectVersion}}.jar'
      jars:
        - directory: 'apps/jreleaser/build/dependencies/flat'
          include: '*.jar'

distributions:
  jreleaser-standalone:
    executable: 'jreleaser'
    docker:
      active: always
      registries:
        - serverName: DEFAULT
      specs:
        slim:
          imageNames:
            - '{{repoOwner}}/{{repoOwner}}-{{dockerSpecName}}:{{tagName}}'
          matchers:
            platform: 'linux'
        alpine:
          imageNames:
            - '{{repoOwner}}/{{repoOwner}}-{{dockerSpecName}}:{{tagName}}'
          matchers:
            platform: 'linux_musl'
```

This configuration:
- assembles 4 cross-platform Java Runtimes with Jlink
- configures a distribution named `jreleaser-standalone`
- configures two docker images
  - 1st image targets ubuntu:latest as it matches `platform: linux`.
  - 2nd image targets alpine:3.13.5 as it matches `platform: linux_musl`
