### ISSUE TITLE
[model] Validation fails with native-image.app.template does not exist.

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#131]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem (link to git repository is ideal)
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

Given the following configuration

```yaml


assemble:
  nativeImages:
    app:
      active: always
      graal: 
        path: /Users/duke/.sdkman/candidates/java/21.0.0.2.r11-grl
      mainJar: 
        path: 'target/{{distributionName}}-{{projectVersion}}.jar'
      jars:
        - directory: target
          exclude: '*-all.jar'
```

### Expected Behaviour
A distribution of type `NATIVE_IMAGE` and name `app` is successfully configured.

### Actual Behaviour
The following error occurs

```
[ERROR] == JReleaser ==
[ERROR] native-image.app.template does not exist. src/jreleaser/assemblers/app/native-image
JReleaser has not been properly configured.
```

### Environment Information

- **Operating System**: N/A
- **JReleaser Version:** 0.3.0
- **JDK Version:** N/A
