### ISSUE TITLE
[hooks] Add a condition property to command and script hooks

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#1364]
Hooks may be filtered by step and become active given the project's version. However, using arbitrary conditions to determine if a hook is executed or not would also be a Good Thing to have.

Example:

```yml
hooks:
  script:
    before:
      - run: './mvnw -ntp verify'
        condition: '"{{ Env.CI }}" == true'
        verbose: true
        filter:
          includes: ['assemble']
```

This hook will be executed given the following conditions match:
- before the `assemble` step.
- `active` has default value `ALWAYS`.
- the `CI` environment variable resolves to `true`.
