### ISSUE TITLE
[release] JReleaser fails to checkout a custom branch

### ISSUE THREAD

**Issue by charphi** [jreleaser/jreleaser#1377]
I'm trying to launch a dry-run on develop branch (snapshots) but it doesn't work anymore on the GitHub release step.  
I'm also confused about the need for JReleaser to checkout branches when skipTag property is set to true. (see below)

### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem (link to git repository is ideal)
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Set property skipTag to false in GitHub release step
1. Modify the default branch in GitHub release step
2. Launch a dry-run

### Expected Behaviour

It was ok with the previous version (v1.5.1).

### Actual Behaviour

It fails in latest version (1.6.0) with the following message:

```
Error:  Failed to execute goal org.jreleaser:jreleaser-maven-plugin:1.6.0:full-release (default) on project sandbox-bom: Execution default of goal org.jreleaser:jreleaser-maven-plugin:1.6.0:full-release failed: Unexpected error when creating release: java.io.IOException: Could not checkout branch master: Ref master cannot be resolved -> [Help 1]
```

Related job: https://github.com/nbbrd/sandbox/actions/runs/4858256136 
Related config: https://github.com/nbbrd/sandbox/blob/983bd7e32a287bb80789a084e1c20a02ad69b6e5/sandbox-bom/pom.xml#L162 

### Environment Information

- **Operating System**: Ubuntu latest (GitHub Actions)
- **JReleaser Version:** 1.6.0
- **JDK Version:** 17

**Comment by aalmiray** [comment]
Unfortunately logs are not being uploaded. Please update your workflows to 

```yml
      - name: Upload JReleaser output
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: jreleaser-release
          path: |
            target/jreleaser/trace.log
            target/jreleaser/output.properties
```

Note the path update as you're using the maven plugin.
