### ISSUE TITLE
[release] JReleaser does not push tag to Github

### ISSUE THREAD

**Issue by triceo** [jreleaser/jreleaser#1425]
I described the issue here: https://github.com/jreleaser/jreleaser/discussions/1424
If I do not push the tag manually in GHA, I get a release that is completely unrelated to any tag.

![image](https://github.com/jreleaser/jreleaser/assets/247403/7d53899c-de68-4998-90a5-5672d90db5e7)

Notice tag info is completely missing. The tag list on Github also doesn't show anything.

The following issue suggests that there may be an issue processing `draft` releases:
https://github.com/jreleaser/jreleaser/issues/1421

I am using `draft` releases here as well. In fact, this is the full configuration:
https://github.com/TimefoldAI/timefold-solver/blob/main/pom.xml#L73

And attached is the trace log.
[trace.log](https://github.com/jreleaser/jreleaser/files/11828932/trace.log)

**Comment by aalmiray** [comment]
A tag is not readily available when a release is published as draft. The release must be updated from draft to non-draft for the tag to become visible.

**Comment by aalmiray** [comment]
Cannot reproduce. Configured the https://github.com/aalmiray/app repository with

```yaml
project:
  name: app
  description: Sample application
  longDescription: Sample application
  links:
    homepage: https://acme.com/awesome-app
  authors:
    - Andres Almiray
  license: Apache-2.0
  java:
    groupId: com.acme
    version: 8
  inceptionYear: 2021
  stereotype: cli

release:
  github:
    draft: true
    overwrite: true
    sign: true
    changelog:
      formatted: 'ALWAYS'
      preset: 'conventional-commits'
      contributors:
        format: '- {{contributorName}}{{#contributorUsernameAsLink}} ({{.}}){{/contributorUsernameAsLink}}'

signing:
  active: always
  armored: true
```

Published a _draft_ release according to the log

```
[INFO]  Releasing to https://github.com/aalmiray/app@main
[DEBUG] fetching all branches on aalmiray/app
[DEBUG] looking up release with tag v1.0.0 at repository aalmiray/app
[DEBUG] fetching release on aalmiray/app with tag v1.0.0
[DEBUG] release v1.0.0 does not exist
[DEBUG] creating release v1.0.0
[DEBUG] tagging local repository with v1.0.0
[DEBUG] creating release on aalmiray/app with tag v1.0.0
[DEBUG] checking if release aalmiray/app@v1.0.0 was left as draft
[DEBUG] fetching release on aalmiray/app with id 109963599
```

Release was successfully left on draft. Next, edited the release using the GitHub UI to make it non-draft, resulting a tag `v1.0.0` and visible, latest release.
