### ISSUE TITLE
[hooks] Add condition support to all hook groups 

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#1538]
**Is your feature request related to a problem? Please describe.**
I'd like to execute certain hooks only when the release is run on CI.

**Describe the solution you'd like**
Adding a `condition` property to all hook groups, for example

```
hooks:
  condition:
  script:
    condition:
    before:
      - run: echo 'foo'
```

**Describe alternatives you've considered**
Single hooks have a `condition` property but that leads to too much repetition, such as

```
hooks:
  script:
    before:
      - condition: '"{{ Env.CI }}" == true'
        filter:
          includes: ['session']
        run: |
          echo "### {{command}}" >> $GITHUB_STEP_SUMMARY
          echo "| Step | Outcome |" >> $GITHUB_STEP_SUMMARY
          echo "| ---- | ------- |" >> $GITHUB_STEP_SUMMARY
    success:
      - condition: '"{{ Env.CI }}" == true'
        run: 'echo "| {{event.name}} | :white_check_mark: |" >> $GITHUB_STEP_SUMMARY'
      - condition: '"{{ Env.CI }}" == true'
        filter:
          includes: ['session']
        run: echo "" >> $GITHUB_STEP_SUMMARY
    failure:
      - condition: '"{{ Env.CI }}" == true'
        run: 'echo "| {{event.name}} | :x: |" >> $GITHUB_STEP_SUMMARY'
      - condition: '"{{ Env.CI }}" == true'
        filter:
          includes: ['session']
        run: |
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Failure" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "{{event.stacktrace}}\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
```

Could be simplified to

```
hooks:
  condition: '"{{ Env.CI }}" == true'
  script:
    before:
      - filter:
          includes: ['session']
        run: |
          echo "### {{command}}" >> $GITHUB_STEP_SUMMARY
          echo "| Step | Outcome |" >> $GITHUB_STEP_SUMMARY
          echo "| ---- | ------- |" >> $GITHUB_STEP_SUMMARY
    success:
      - run: 'echo "| {{event.name}} | :white_check_mark: |" >> $GITHUB_STEP_SUMMARY'
      - filter:
          includes: ['session']
        run: echo "" >> $GITHUB_STEP_SUMMARY
    failure:
      - run: 'echo "| {{event.name}} | :x: |" >> $GITHUB_STEP_SUMMARY'
      - filter:
          includes: ['session']
        run: |
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Failure" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "{{event.stacktrace}}\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
```
