### ISSUE TITLE
[changelog] Identify commit labels by authors or committers

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#1543]
Add an option to label commits by their authors/contributors/committers such as

```yaml
release:
  github:
    overwrite: true
    changelog:
      formatted: ALWAYS
      preset: conventional-commits 
      labelers:
        - label: hideme
          contributor: aalmiray
```
