### ISSUE TITLE
Support multiple matchers for labels

### ISSUE THREAD

**Issue by netomi** [jreleaser/jreleaser#1550]
Right now, a single matcher is supported for items like the title or the body like explained in the documentation:

```
labelers:
          # The label to be applied.
          # 
        - label: 'issue'

          # Matches the text of the first commit line.
          # Value may be plain text or regex.
          # Use `regex:` as prefix to indicate a regex.
          # 
          title: 'regex:fix:'

          # Matches the full text of the commit.
          # Value may be plain text or regex.
          # Use `regex:` as prefix to indicate a regex.
          # 
          body: 'Fixes #'
```

it would be quite handy to additionally support a list of matchers like that:

```
  - label: 'dependencies'
    title:
      - 'regex:deps:i'
      - 'regex:dependencies:i'
      - 'regex:bump:i'
```

where if any of the matchers matches, the label will be applied. Additionally, support adding a flag after the second colon to be able to express case-insenstive pattern. This would be similar to the javascript notation of '/bump:/i'.

The notation for the flag might not work in a backwards compatible way, but having the possibility to express case-insensitive pattern in an easy way would be certainly useful imho.
