### ISSUE TITLE
[assemble] Support custom JAVA_OPTS values in jlink launcher

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#1553]
Similarly as it's done for the `java-archive` assembler, the contents of `java.options` should be honored and used as input for `$JAVA_OPTS`.

```yaml
assemble:
  jlink:
    helloworld:
      active: ALWAYS
      imageName: '{{distributionName}}-{{projectVersion}}'
      java:
        options: -XX:+UseZGC -Xmx128m --enable-preview
```
