### ISSUE TITLE
[packagers] SkipTemplates in a packager versus SkipTemplates in a distribution [bug?]

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#1584]
### Discussed in https://github.com/jreleaser/jreleaser/discussions/1583

<div type='discussions-op-text'>

<sup>Originally posted by **haydenbaker** January 30, 2024</sup>
I noticed that, when defining templates to skip in a packager at the top level, it doesn't actually do anything - the templates/files still get used and packaged:
```
    packagers {
        brew {
            active = 'ALWAYS'
            skipTemplates = ["README.*"]
        }
    }
```

However, when declaring template-skips under a distribution, they _do_ get skipped. 
```
    distributions {
        xyz {
            ...
            brew {
                active = 'ALWAYS'
                skipTemplates = ["README.*"]
            }
        ...
```

In the trace (for the first example), I see that the top-level packager has `skipTemplates` set, but in the packager for the distribution, `skipTemplates` is missing. FWIW, if I set a template-directory at the top-level, it gets propagated to the distribution-packager.

Is this a bug, or is this intended?</div>

How to reproduce:
1. git clone https://github.com/jreleaser/helloworld-java-bin.git
2. edit `jreleaser.yml` by adding
```yaml
packagers:
  brew:
    active: ALWAYS
    skipTemplates:
      - README.*
```
3. build it with `./mvnw verify`
4. assemble it with `jreleaser assemble`
5. check the resolved configuration with `jreleaser config`

Relevant bits from the configuration output

```
packagers:
    brew:
        enabled: true
        active: ALWAYS
        continueOnError: false
        skipTemplates:
            README.*
        commitAuthor:
            name: jreleaserbot
            email: jreleaser@kordamp.org
        multiPlatform: false
        repository:
            enabled: false
            owner: jreleaser
            name: homebrew-tap
            tagName: v{{projectVersion}}
            branch: HEAD
            branchPush: HEAD
            username: jreleaser
            token: ************
        cask:
            enabled: false

distributions:
    helloworld:
        enabled: true
        active: ALWAYS
        type: JAVA_BINARY
        executable:
            name: helloworld
            windowsExtension: bat
        artifacts:
            artifact 0:
                enabled: true
                active: ALWAYS
                path: /Users/aalmiray/dev/github/helloworld-java-bin/out/jreleaser/assemble/helloworld/java-archive/helloworld-1.0.0-SNAPSHOT.zip
        stereotype: CLI
        java:
            enabled: true
            version: 11
            groupId: org.jreleaser.examples
            artifactId: helloworld
            mainClass: org.jreleaser.examples.HelloWorld
            multiProject: false
        brew:
            enabled: true
            active: ALWAYS
            continueOnError: false
            templateDirectory: src/jreleaser/distributions/helloworld/brew
            commitAuthor:
                name: jreleaserbot
                email: jreleaser@kordamp.org
            formulaName: helloworld
            multiPlatform: false
            repository:
                enabled: false
                active: RELEASE
                owner: jreleaser
                name: homebrew-tap
                tagName: v{{projectVersion}}
                branch: HEAD
                branchPush: HEAD
                username: jreleaser
                token: ************
                commitMessage: {{distributionName}} {{tagName}}
            cask:
                enabled: false
```

Showing that `skipTemplates` was not inherited.
