### ISSUE TITLE
[packagers] Specify projectIdentifier for brew's repository when publishing to GitLab

### ISSUE THREAD

**Issue by jacobk** [jreleaser/jreleaser#1621]
**Is your feature request related to a problem? Please describe.**
It's currently not possible to specify a GitLab projectIdentifier for the repository used to publish a brew package.

This can currently lead to brew packages being published to the same repository as the release when using `projectIdentifier` in the release config.

For more context see discussion: https://github.com/jreleaser/jreleaser/discussions/1620

**Describe the solution you'd like**
Make it possible to configure a GitLab specific projectIdentifier for the brew packager's repository

**Comment by jacobk** [comment]
Hello!

I'm trying to use the early access build to test this features

```
jbang jreleaser-snapshot@jreleaser --version
------------------------------------------------------------
jreleaser 1.12.0-SNAPSHOT
------------------------------------------------------------
Build time:   2024-03-25 19:38:09+01:00
Revision:     d63968a68fce267236da0e7a8d5d309ae47068c2
JVM:          17.0.10 (Oracle Corporation 17.0.10+11-LTS-jvmci-23.0-b27)
------------------------------------------------------------
```

My `jreleaser.yml` includes:
```
release:
  gitlab:
#    overwrite: true
    host: gitlab.com
    projectIdentifier: <id 1>
    changelog:
      formatted: ALWAYS
      preset: 'conventional-commits'
      skipMergeCommits: true
      format: '- {{commitShortHash}} {{commitTitle}}'
      extraProperties:
        categorizeScopes: true
      append:
        enabled: true

packagers:
  brew:
    active: ALWAYS
    repository:
      extraProperties:
        projectIdentifier: <id 2>
    extraProperties:
      skipJava: true
```

But when I run publish I still get:
```
[INFO]    - Publishing foobar distribution
[INFO]      [brew] publishing foobar distribution
[DEBUG]     [brew] creating props for foobar/brew
[DEBUG]     [brew] filling distribution properties into props
[DEBUG]     [brew] filling git properties into props
[DEBUG]     [brew] filling artifact properties into props
[DEBUG]     [brew] filling packager properties into props
[INFO]      [brew] setting up repository xyz/homebrew-tap # <--- (the full path of this in gitlab is something like /acme/team/xyz/homebrew-tap )
[DEBUG]     [brew] locating repository xyz/homebrew-tap
[DEBUG]     [brew] lookup repository xyz/homebrew-tap
[DEBUG]     [brew] fetching project with GitLab id <id 1> # <--- NB. This is not the correct projectIdentifier
[DEBUG]     [brew] found Acme / teams / xyz / foobar (ID: <id 1>)
[DEBUG]     [brew] cloning https://gitlab.com/acme/team/xyz/foobar.git # <--- This is not "xyz/homebrew-tap"
[DEBUG]     [brew] copying files from out/jreleaser/package/foobar/brew
[DEBUG]     [brew] copying files from /xxx/foobar/out/jreleaser/package/foobar/brew to /var/folders/mn/2wmbd0tx61g_fdxs4vb0dcrw0000gp/T/jreleaser-homebrew-tap7127561573156636738
[DEBUG]     [brew] setting up commit
[DEBUG]     [brew] tagging local repository with v2024.1.0
[INFO]      [brew] pushing to https://gitlab.com/acme/team/xyz/foobar.git
[DEBUG]     [brew] pushing commit to remote
```

And this still goes on and overwrites the wrong repo.

**Comment by aalmiray** [comment]
```
[INFO]      [brew] setting up repository xyz/homebrew-tap # <--- (the full path of this in gitlab is something like /acme/team/xyz/homebrew-tap )
[DEBUG]     [brew] locating repository xyz/homebrew-tap
[DEBUG]     [brew] lookup repository xyz/homebrew-tap
[DEBUG]     [brew] fetching project with GitLab id <id 1>
```

The first 3 lines use `xyz/homebrew-tap` as that is the expectation by the conventions. However, we know the path will be different. The 4th line is where the `projectIdentifier` should be resolved. At this point the wrong id has been used

https://github.com/jreleaser/jreleaser/blob/d63968a68fce267236da0e7a8d5d309ae47068c2/sdks/jreleaser-gitlab-java-sdk/src/main/java/org/jreleaser/sdk/gitlab/GitlabReleaser.java#L186-L196

This code attempts to find a `projectIdentifier`(for the packager's repository) in the extra properties, defaulting to the project's identifier. This is wrong. If no `projectIdentifier` is found for the repository then it should attempt to find it by owner/name. We know this will fail in a nested scenario as yours, in which case specifically defining the owner as `acme/team/xyz` might be the way to go for now.

Reopening to fix the use of default `projectIdentifier`.

**Comment by aalmiray** [comment]
I've found the problem, you can see it too in the resolved mode (look at `trace.log` or run the `config` command): the extra properties defined in the `packagers` section are not copied to the distribution packagers, that is, given the following configuration:

```
packagers:
  brew:
    active: always
    repository:
      extraProperties:
        projectIdentifier: 27846682

distributions:
  app:
    artifacts:
      - path: target/distributions/{{distributionName}}/{{distributionName}}-{{projectVersion}}.zip
      - path: target/distributions/{{distributionName}}/{{distributionName}}-{{projectVersion}}.tar.gz
```

Results in the following resolved model:

```
packagers:
    brew:
        enabled: true
        active: ALWAYS
        continueOnError: false
        commitAuthor:
            name: jreleaserbot
            email: jreleaser@kordamp.org
        multiPlatform: false
        repository:
            enabled: false
            owner: aalmiray
            name: homebrew-tap
            tagName: v{{projectVersion}}
            branch: HEAD
            branchPush: HEAD
            username: aalmiray
            token: ************
            extraProperties:
                projectIdentifier: 27846682
        cask:
            enabled: false

distributions:
    app:
        enabled: true
        active: ALWAYS
        type: JAVA_BINARY
        executable:
            name: app
            windowsExtension: bat
        artifacts:
            artifact 0:
                enabled: true
                active: ALWAYS
                path: target/distributions/app/app-1.0.0.zip
            artifact 1:
                enabled: true
                active: ALWAYS
                path: target/distributions/app/app-1.0.0.tar.gz
        stereotype: NONE
        java:
            enabled: true
            version: 8
            groupId: com.acme
            artifactId: app
            multiProject: false
        brew:
            enabled: true
            active: ALWAYS
            continueOnError: false
            templateDirectory: src/jreleaser/distributions/app/brew
            commitAuthor:
                name: jreleaserbot
                email: jreleaser@kordamp.org
            formulaName: app
            multiPlatform: false
            repository:
                enabled: true
                active: RELEASE
                owner: aalmiray
                name: homebrew-tap
                tagName: v{{projectVersion}}
                branch: HEAD
                branchPush: HEAD
                username: aalmiray
                token: ************
                commitMessage: {{distributionName}} {{tagName}}
            cask:
                enabled: false
```

Note the missing extra properties in the distribution packager.
