### ISSUE TITLE
[core] Reduce Required Metadata

### ISSUE THREAD

**Issue by bowbahdoe** [jreleaser/jreleaser#1706]
**Is your feature request related to a problem? Please describe.**
I now have this project, for which I am using `jreleaser` to publish artifacts.

https://github.com/bowbahdoe/tools

I am a little annoyed at needing to repeat information inside my `jreleaser.yml` that I already have to specify explicitly inside my `pom.xml`s or for which I don't see how it is relevant.

I.E. most of this section.
```
project:
  name: tool
  version: 2024.08.25.5
  description: API for working directly with CLI tools.
  longDescription: API for working directly with CLI tools.
  links:
    homepage: https://github.com/bowbahdoe/tools
  authors:
    - Ethan McCue
  license: APACHE-2.0
  inceptionYear: 2024
  versionPattern: CHRONVER
  java:
    mainModule: dev.mccue.tools
    groupId: dev.mccue
```

**Describe the solution you'd like**
I'd like to be able to leave off most of this. I understand needing to specify `CHRONVER` because by default you want versions to go `1.2.3`, but i'm unclear the utility of the rest (to me)

**Describe alternatives you've considered**

Just dealing with it.

**Additional context**

I am not most users and I am using the jreleaser cli directly like a weirdo. You don't need to weigh my complaints heavily.
