### ISSUE TITLE
[deploy] Unable to tell jreleaser to deploy without making a release

### ISSUE THREAD

**Issue by TimothyJones** [jreleaser/jreleaser#1742]
**Is your feature request related to a problem? Please describe.**

I already have a release workflow (separate). I'd like to use JReleaser just to sign + publish to maven central for me. As far as I can tell, there's no way to disable the release step, so `jreleaserRelease` complains that it doesn't have a github token.

I worked around this by setting `JRELEASER_GITHUB_TOKEN=empty`, which lets me publish to maven central - but once that's successful, gradle always fails when trying to publish to github.

**Describe the solution you'd like**

I'd like an ability to tell JReleaser never to run the release step when running `jreleaserRelease`.

**Describe alternatives you've considered**

I've tried setting `release { github { enabled = false } }`, but it fails with 

```
> JReleaser has not been properly configured.
  No release provider has been configured
```

I've tried setting skip publish and skip tag, but it fails on invalid the github token - and I don't want to give it a real live token in case it does anything.

**Additional context**

Great tool otherwise, I really appreciate the care that you've put into the config and error printing.

**Comment by TimothyJones** [comment]
Update: perhaps I should be using `jreleaserPublish` instead? These docs [suggest](https://jreleaser.org/guide/latest/concepts/workflow.html#_publish) it doesn't depend on release?

Having said that, I still can't run `jreleaserConfig` without a release step enabled (or a token configured) - so I think the feature request is still valid.

**Comment by TimothyJones** [comment]
Ah, of course it is 😆  Thanks!

> An empty GitHub token is a good workaround for the time being if you invoke jreleaserRelease.

Yep! The main problem is not being able to invoke `jreleaserConfig` (which I can with this workaround).

**Comment by aalmiray** [comment]
`jreleaserConfig` is the first check against potential errors, as such it should fail early. I have to double check if `strict` mode relaxes checks during config evaluation or not.

**Comment by aalmiray** [comment]
Release configuration is no longer needed when performing deployments in a standalone fashion.

Here's an example

```yaml
project:
  name: helloworld
  description: HelloWorld in Java
  longDescription: HelloWorld in Java
  links:
    homepage: https://github.com/jreleaser/helloworld-java-bin
  authors:
    - Andres Almiray
  license: APACHE-2.0
  inceptionYear: 2023
  stereotype: CLI
  languages:
    java:
      version: 11
      groupId: org.jreleaser.examples
      artifactId: helloworld
      mainClass: org.jreleaser.examples.HelloWorld

signing:
  active: ALWAYS
  armored: true

deploy:
  maven:
    mavenCentral:
      release-deploy:
        active: RELEASE
        url: https://central.sonatype.com/api/v1/publisher
        stagingRepositories:
          - target/staging-deploy
    nexus2:
      snapshot-deploy:
        active: SNAPSHOT
        snapshotUrl: https://central.sonatype.com/repository/maven-snapshots/
        applyMavenCentralRules: true
        snapshotSupported: true
        closeRepository: true
        releaseRepository: true
        stagingRepositories:
          - target/staging-deploy
```
