### ISSUE TITLE
[model] Add a copyright field to project

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#180]
This filed may be used to define a value such as "2020 The original authors".
If left blank will trigger a validation error.

Alternatively, define 

```
project:
  extraProperties:
    inceptionYear: 2020
  authors:
    - Duke
```

Which would result in a resolved copyright as `2020 Duke`.
