### ISSUE TITLE
[deploy] failed to gradle publish to maven central if version is snapshot

### ISSUE THREAD

**Issue by Doc94** [jreleaser/jreleaser#1823]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [X] Example that reproduces the problem (link to git repository is ideal)
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. In maven central create a namespace and enable snapshot
2. Run gradle to publish (example for the build https://pastes.dev/nYiAsIkymu)

### Expected Behaviour

Upload the artifact and pass to release in central

### Actual Behaviour

Upload the artifact and Maven Central deny based in snapshot version

### Environment Information

- **Operating System**: Windows 11
- **JReleaser Version:** 1.17.0
- **JDK Version:** 21

not sure if is a bug from JRelease or maven central when check...

[trace.log](https://github.com/user-attachments/files/19040934/trace.log)

**Comment by aalmiray** [comment]
Did you enable snapshot publications at the Sonatype portal? https://central.sonatype.org/publish/publish-portal-snapshots/

**Comment by aalmiray** [comment]
You also have to use a different URL, `https://central.sonatype.com/repository/maven-snapshots`.

**Comment by Doc94** [comment]
> Did you enable snapshot publications at the Sonatype portal? https://central.sonatype.org/publish/publish-portal-snapshots/

Yes
![image-10.png](https://github.com/user-attachments/assets/bddc76d6-4323-4252-b854-c95fbeae642c)

**Comment by Doc94** [comment]
> You also have to use a different URL, `https://central.sonatype.com/repository/maven-snapshots`.

Im a little lost in that i based in the JRelease docs with the stagged publish, and if use this in the url in replace of publish api just get a 403 error. Then not sure where need to put that repo url when is a snapshot

**Comment by aalmiray** [comment]
We may need to find out more information about the endpoint and API required for snapshot publication. Looks like it's not the same for regular publications.

**Comment by Doc94** [comment]
> We may need to find out more information about the endpoint and API required for snapshot publication. Looks like it's not the same for regular publications.

yeah i make a few test and i make work just set the url in the maven publish but feels strange not use the stage for snapshots and use jrelease for "final" versions

**Comment by Doc94** [comment]
Hi, any news about this?
still dont like the workaround for make two workflows based in SNAPSHOT or not...

**Comment by aalmiray** [comment]
I'm afraid it's not a workaround. This is the way to make it work according to Sonatype due to how they have implemented their REST endpoints.

**Comment by aalmiray** [comment]
The purpose of that flag comes from the common behavior shared by all deployers. That flag was erroneously made mutable for the `mavenCentral` deployer. It will be reverted to immutable (and set to `false`) in the next release. 

Also, the documentation will be updated with an example on how to configure deployments to the Maven Central Portal.

**Comment by ThomasVitale** [comment]
I'm using the following configuration to publish production artefacts using the new Publisher API and snapshots using the old Nexus API:

```
deploy:
  maven:
    mavenCentral:
      sonatype:
        active: RELEASE
        url: "https://central.sonatype.com/api/v1/publisher"
        applyMavenCentralRules: true
        retryDelay: 20
        maxRetries: 100
        stagingRepositories:
          - build/staging-deploy
    nexus2:
      central:
        active: SNAPSHOT
        applyMavenCentralRules: true
        snapshotUrl: https://central.sonatype.com/repository/maven-snapshots/
        snapshotSupported: true
        closeRepository: true
        releaseRepository: true
        stagingRepositories:
          - build/staging-deploy
``` 

The Central Portal documentation mentions the following (https://central.sonatype.org/publish/publish-portal-snapshots/#publishing-snapshot-releases-for-your-project):

> Because publishing -SNAPSHOT releases does not perform validation on the component(s), a mvn deploy-compatible API was chosen for maximum ecosystem compatibility.

Hard to tell if it's a permanent solution of if there will be an alternative for using the Publisher API in the future.
