### ISSUE TITLE
[assemble] Add --launcher-as-aservice flag to jpackage assembler

### ISSUE THREAD

**Issue by fer-marino** [jreleaser/jreleaser#1912]
I'm setting up a yml file to do a release, and in the jpackage section I don't find anything that would allows me to set the option --launcher-as-service, see here https://docs.oracle.com/en/java/javase/21/docs/specs/man/jpackage.html

My understanding is that support for this flag is not available yet. Would be nice to have this extra option in the dsl

thanks you
Fernando

**Comment by aalmiray** [comment]
🎉 This issue has been resolved in `v1.20.0` ([Release Notes](https://github.com/jreleaser/jreleaser/releases/tag/v1.20.0))

**Comment by fer-marino** [comment]
hi, thank you for this but... it doesn't work :D
the fragment of my jreleaser.yml
```
assemble:
  jlink:
    opf-jlink:
      java:
        version: "21"
      active: ALWAYS
      exported: false
      executable: opf
      stereotype: WEB
      jdeps:
        multiRelease: "21"
        ignoreMissingDeps: true
      copyJars: false

      mainJar:
        path: 'build/libs/osm-{{projectVersion}}.jar'
  jpackage:
    opf:
      jlink: opf-jlink
      exported: true
      active: ALWAYS
      applicationPackage:
        #  appName: opf
        appVersion: '{{projectVersionNumber}}'
        vendor: Starion Group S.A.
        launcherAsService: true
```

this normally works, I've just added the `launcherAsService` entry as described in the doc. 

The error I get is:

```
Unrecognized field "launcherAsService" (class org.jreleaser.model.internal.assemble.JpackageAssembler$ApplicationPackage), not marked as ignorable (6 known properties: "appVersion", "vendor", "appName", "licenseFile", "fileAssociations", "copyright"])
 at [Source: UNKNOWN; line: 69, column: 32] (through reference chain: org.jreleaser.model.internal.JReleaserModel["assemble"]->org.jreleaser.model.internal.assemble.Assemble["jpackage"]->java.util.LinkedHashMap["opf"]->org.jreleaser.model.internal.assemble.JpackageAssembler["applicationPackage"]->org.jreleaser.model.internal.assemble.JpackageAssembler$ApplicationPackage["launcherAsService"])

```
