### ISSUE TITLE
JReleaser 0.1.0 not found

### ISSUE THREAD

**Issue by anyulled** [jreleaser/jreleaser#25]
Hi, thanks for this valuable tool.

I'm trying to configure a continuous integration pipeline following this [instructions](https://jreleaser.org/guide/latest/continuous-integration/gitlab-ci.html).

This is an extract of my pipeline configuration:

```yaml
download-jreleaser:
  image: azul/zulu-openjdk:11
  stage: test
  script:
    - java get_jreleaser.java "0.1.0"
    - java -jar jreleaser-cli.jar --version
  artifacts:
    paths:
      - jreleaser-cli.jar
```

Nonetheless, when I get to the **download-jreleaser** stage I get this error, both on the CI environment with Ubuntu and my local windows 10 machine:

```bash
java get_jreleaser.java
✅ Located version marker
✅ JReleaser latest resolves to 0.1.0
❌ JReleaser 0.1.0 not found
```

I'd like to know if I'm missing something on my side, I'm using Java SDK v.11

```bash
java -version
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9+11)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.23.0, JRE 11 Windows 10 amd64-64-Bit Compressed References 20201022_795 (JIT enabled, AOT enabled)
OpenJ9   - 0394ef754
OMR      - 582366ae5
JCL      - 3b09cfd7e9 based on jdk-11.0.9+11)
```
