### ISSUE TITLE
[assemble] Let the name of the nativeImage directory be configurable

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#272]
For a project configured as

```yaml
project:
  version: 1.0.0-SNAPSHOT
  description: Sample application
  longDescription: Sample application
  website: https://github.com/aalmiray/app
  authors:
    - Andres Almiray
  license: Apache-2.0
  java:
    groupId: com.acme
    version: 8
  extraProperties:
    inceptionYear: 2021

distributions:
  app:
    artifacts:
      - path: target/distributions/{{distributionName}}/{{distributionName}}-{{projectVersion}}.zip

assemble:
  nativeImage:
    app-native:
      active: always
      exported: false
      executable: app
      graal: 
        path: /Users/aalmiray/.sdkman/candidates/java/21.1.0.r11-grl
      mainJar: 
        path: 'target/app-{{projectVersion}}.jar'
```

The assembled artifact will be named `app-link-1.0.0-SNAPSHOT.zip`, with a top level directory `app-link-1.0.0-SNAPSHOT` (once https://github.com/jreleaser/jreleaser/issues/271 is fixed). Both filename and top level directory could have a different name. 

Add a property to specify this name.
