### ISSUE TITLE
[upload] Apply naming convention to extra headers added to Http uploader

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#280]
Artifact properties will be added as headers when uploading to Http. Property keys should follow a well defined format.
Proposal: `X-<name-in-all-caps>` 

If name is camelCase then words will be separated by a `-`, such that

```yaml
artifacts:
  - path: path/to.app-1.0.0.zip
    platform: osx
    extraProperties:
      foo: bar
      fooBar: foobar
```

Results in the following headers

 * `X-PLATFORM`: osx
 * `X-FOO`: bar
 * `X-FOO-BAR`: foobar
