### ISSUE TITLE
[model] Add formatted version properties

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#310]
Given a project with version `12.3.0-SNAPSHOT` and a snapshot label `{{{{projectVersionNumber}}.EarlyAccess}}` the following properties should become available

```yaml
    extraProperties:
        # existing
        projectVersionMajor: 12
        projectVersionMinor: 3
        projectVersionPatch: 0
        projectVersionNumber: 12.3.0
        projectVersionTag: SNAPSHOT
        # new
        projectVersionWithUnderscores: 12_3_0_SNAPSHOT
        projectVersionWithDashes: 12-3-0-SNAPSHOT
        projectVersionNumberWithUnderscores: 12_3_0
        projectVersionNumberWithDashes: 12-3-0
        projectEffectiveVersionWithUnderscores: 12_3_0_EarlyAccess
        projectEffectiveVersionWithDashes: 12-3-0-EarlyAccess
```
