### ISSUE TITLE
[announce] Add a file template announcer

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#312]
The input is a file (or files) template that will be committed to a target Git repository

```yml
announce:
  article:
    active: always
    repository:
      owner: app
      name: docs
    files:
      - path: 'post.adoc'
        transform: '_posts/{{#f_now}}YYYY-MM-dd{{/f_now}}/{{projectName}}-{{#f_dash}}{{projectVersion}}{{/f_dash}}-released.adoc'
```

Suggested by @maxandersen
