### ISSUE TITLE
[model] Align artifacts and globs

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#323]
Both `Artifact` and `Glob` define files that may be consumed by other model elements however they do not provide common options, for example globs can't have extra properties. Also, globs require too much setup, it would be better to use a glob pattern directly, such as

```
files:
  artifacts:
    - path: path/to/the/file.txt
   globs:
    - pattern: docs/**/*.adoc
```

This also opens the door for allowing name templates in a glob's pattern.
