### ISSUE TITLE
[changelog] contributor.format is ignored

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#332]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem (link to git repository is ideal)
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Configure changelog formating options using the Maven plugin as shown

```xml
          <plugin>
            <groupId>org.jreleaser</groupId>
            <artifactId>jreleaser-maven-plugin</artifactId>
            <version>0.6.0</version>
            <inherited>false</inherited>
            <configuration>
              <jreleaser>
                <release>
                  <github>
                    <skipTag>true</skipTag>
                    <changelog>
                      <formatted>ALWAYS</formatted>
                      <format>- {{commitShortHash}} {{commitTitle}}</format>
                      <contributors>
                        <format>* {{contributorName}}{{#contributorUsernameAsLink}} ({{.}}){{/contributorUsernameAsLink}}</format>
                      </contributors>
                      <hide>
                        <contributors>
                          <contributor>GitHub</contributor>
                          <contributor>bot</contributor>
                        </contributors>
                      </hide>         
                    </changelog>
                  </github>
                </release>
              </jreleaser>
            </configuration>
          </plugin>
```

### Expected Behaviour

Contributors should be formatted as expected.

### Actual Behaviour

Format options are ignored. Invoking `jreleaser:config` shows that format options were not set

```
        changelog:
            enabled: true
            links: false
            sort: DESC
            formatted: always
            format: - {{commitShortHash}} {{commitTitle}}
            content: 
## Changelog

{{changelogChanges}}
    {{changelogContributors}}
            hide:
                uncategorized: false
                contributors:
                    GitHub
                    bot
            contributors:
                enabled: true
            categories:
                category 0:
                    title: 🚀 Features
                    labels:
                        feature
                        enhancement
                category 1:
                    title: 🐛 Bug Fixes
                    labels:
                        bug
                        fix
```

### Environment Information

- **Operating System**: TODO
- **JReleaser Version:** 0.6.0
- **JDK Version:** TODO
