### ISSUE TITLE
[brew] Cask is generated instead of a Formula for BINARY distribution

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#337]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem (link to git repository is ideal)
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Configure a project as shown
```yml
packagers:
  brew:
    active: always

distributions:
  app:
    type: BINARY
    artifacts:
      - path: target/distributions/{{distributionName}}/{{distributionName}}-{{projectVersion}}.zip
        platform: osx-x86_64
````

### Expected Behaviour

A formula should be generated

```yml
distributions:
    app:
        enabled: true
        active: always
        type: BINARY
        executable: app
        artifacts:
            artifact 0:
                path: target/distributions/app/app-1.0.0.zip
                platform: osx-x86_64
        brew:
            enabled: true
            active: always
            continueOnError: false
            templateDirectory: src/jreleaser/distributions/app/brew
            commitAuthor:
                name: jreleaserbot
                email: jreleaser@kordamp.org
            formulaName: app
            multiPlatform: false
            tap:
                owner: aalmiray
                name: homebrew-tap
                branch: HEAD
                username: aalmiray
                token: ************
            cask:
                enabled: false
```

### Actual Behaviour

A cask is generated

```yml
distributions:
    app:
        enabled: true
        active: always
        type: BINARY
        executable: app
        artifacts:
            artifact 0:
                path: target/distributions/app/app-1.0.0.zip
                platform: osx-x86_64
        brew:
            enabled: true
            active: always
            continueOnError: false
            templateDirectory: src/jreleaser/distributions/app/brew
            commitAuthor:
                name: jreleaserbot
                email: jreleaser@kordamp.org
            formulaName: app
            multiPlatform: false
            tap:
                owner: aalmiray
                name: homebrew-tap
                branch: HEAD
                username: aalmiray
                token: ************
            cask:
                enabled: true
                name: app
                displayName: App
````

### Environment Information

- **Operating System**: N/A
- **JReleaser Version:** 0.6.0
- **JDK Version:** N/A

**Comment by aalmiray** [comment]
Workaround: explicitly disable the cask

Once https://github.com/jreleaser/jreleaser/issues/336 is fixed:

```yml
packagers:
  brew:
    active: always
    cask:
      enabled: false

distributions:
  app:
    type: BINARY
    artifacts:
      - path: target/distributions/{{distributionName}}/{{distributionName}}-{{projectVersion}}.zip
        platform: osx-x86_64
```


Or directly at the distribution level
```yml
distributions:
  app:
    type: BINARY
    brew:
      active: always
      cask:
        enabled: false
    artifacts:
      - path: target/distributions/{{distributionName}}/{{distributionName}}-{{projectVersion}}.zip
        platform: osx-x86_64
```
