### ISSUE TITLE
[model] Harmonize update, prerelease, and snapshot sections

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#339]
Turn `update` and `prerelease` into their own sections, such that

```yml
release:
  github:
    update:
      enabled: true
      sections:
        - ASSETS
     prerelease:
       enabled: true
```

Affects model and auto-config release.

Related to https://github.com/jreleaser/jreleaser/issues/335
Follow up to https://github.com/jreleaser/jreleaser/issues/307
