### ISSUE TITLE
[core] Artifact transforms always copies the source file

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#377]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem (link to git repository is ideal)
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Given a project with the given configuration
```yaml
distributions:
  app:
    artifacts:
      - path: 'target/{{distributionName}}-{{projectVersion}}.zip'
        transform: '{{projectVersion}}.zip'
```

When releasing a copy of the original artifact is created using the given transform.

### Expected Behaviour

Invoking release twice should not create a copy the second time.

### Actual Behaviour

A copy is created on every invocation.

### Environment Information

- **Operating System**: N/A
- **JReleaser Version:** 0.6.0
- **JDK Version:** N/A
