### ISSUE TITLE
[changelog] Support explicit regex in labeler's label

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#386]
The value for `labeler.label` does not accept an explicit regex.
Use the `regex:` prefix to be consistent with glob patterns.

Thus, the following will match all issue numbers explicitly found in the title:

```yaml
release:
  github:
    changelog:
      formatted: ALWAYS
      labelers:
        - label: 'issue'
          title: 'regex:.*#[0-9].*'
      categories:
        - title: '✅ Issues'
          labels:
            - 'issue'
```
