### ISSUE TITLE
[changelog] category specific format

### ISSUE THREAD

**Issue by andreabettich** [jreleaser/jreleaser#429]
**Is your feature request related to a problem? Please describe.**
It would be nice to have a different formatting for the different categories.\
Say for breaking changes, which have some more context in the commit body, it should write out the whole body and not just the title.

**Describe the solution you'd like**
````
      categories:
        - title: '💣 Breaking Changes'
          format: - "{{commitShortHash}} {{commitBody}}"
          labels:
            - 'breaking'
```

**Describe alternatives you've considered**
-

**Additional context**
-
