### ISSUE TITLE
[changelog] Add icons to categories defined by presets

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#448]
cc @maxandersen

**Comment by aalmiray** [comment]
As a temporary workaround you may use replacers to add icons to categories, for example

```yaml
release:
  github:
    overwrite: true
    changelog:
      formatted: ALWAYS
      preset: 'conventional-commits'
      format: '- {{commitShortHash}} {{commitTitle}}'
      replacers:
        - search: 'Documentation'
          replace: '📝 Documentation'
```
