### ISSUE TITLE
[brew] Custom templateDirectory is not honored

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#480]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem (link to git repository is ideal)
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a template directory such as `etc/templates/brew/neo4j-migrations`
2. Configure the template in JReleaser such as
```yaml
packagers:
  brew:
    active: always
    templateDirectory: etc/templates/brew/neo4j-migrations
```
3. Print out the resolved model by invoking the `config` command.

### Expected Behaviour

The custom template directory appears in the configuration.

### Actual Behaviour

The default template directory appears instead.

```yaml
packagers:
    brew:
        enabled: true
        active: always
        continueOnError: false
        templateDirectory: etc/templates/brew/neo4j-migrations
```

### Environment Information

- **Operating System**: N/A
- **JReleaser Version:** 0.8.0
- **JDK Version:** N/A

Please paste stacktraces from `[out|build|target]/jreleaser/trace.log`.
