### ISSUE TITLE
[core] Resolve paths with nested templates

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#482]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem (link to git repository is ideal)
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Define an environment variable with a name template.
2. Use that variable in a path.
3. Execute `jreleaser config`.

```yaml
environment:
  properties:
    jdkPathPrefix: '{{outputDirectory}}/jdks'
    jdkFilePrefix: 'zulu11.48.21-ca-jdk11.0.11'

assemble:
  jlink:
    q-cli:
      active: always
      java:
        version: 11
        mainClass: 'io.quarkus.bootstrap.runner.QuarkusEntryPoint'
      imageName: '{{distributionName}}-{{projectVersion}}'
      targetJdks:
        - path: '{{jdkPathPrefix}}/zulu11Osx/{{jdkFilePrefix}}-macosx_x64/zulu-11.jdk/Contents/Home'
          platform: 'osx-x86_64'
        - path: '{{jdkPathPrefix}}/zulu11Linux/{{jdkFilePrefix}}-linux_x64'
          platform: 'linux_musl-x86_64'
        - path: '{{jdkPathPrefix}}/zulu11Windows/{{jdkFilePrefix}}-win_x64'
          platform: 'windows-x86_64'
      copyJars: false
      jdeps:
        multiRelease: base
        ignoreMissingDeps: true
      args:
        - '--bind-services'
      mainJar:
        path: '{{outputDirectory}}/quarkus-app/quarkus-run.jar'
      jars:
        - pattern: '{{outputDirectory}}/quarkus-app/lib/**/*.jar'
      fileSets:
        - input: '{{outputDirectory}}/quarkus-app'
```

### Expected Behaviour

The path is resolved correctly.

### Actual Behaviour

The variable name template failed to evaluate.

```
Path does not exist. {{outputDirectory}}/jdks/zulu11Linux/zulu11.48.21-ca-jdk11.0.11-linux_x64
```

### Environment Information

- **Operating System**: N/A
- **JReleaser Version:** 0.8.0
- **JDK Version:** N/A
