### ISSUE TITLE
[gradle] Unable to declare more than one artifact in distributions

### ISSUE THREAD

**Issue by itzg** [jreleaser/jreleaser#558]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem (link to git repository is ideal)
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. In `gradle.build` added the following to do the equivalent before #515
```
jreleaser {
    distributions {
        app {
            artifacts {
                artifact {
                    path = "build/distributions/{{projectName}}-{{projectVersion}}.tgz"
                }
                artifact {
                    path = "build/distributions/{{projectName}}-{{projectVersion}}.zip"
                }
            }
        }
    }
```
2. Run `./gradlew jreleaserConfig`

### Expected Behaviour

Expected two artifacts ("artifact 0" and "artifact 1") to be shown in the following output:
```
distributions:
    app:
        enabled: true
        active: always
        type: JAVA_BINARY
        executable: app
        executableExtension: bat
        artifacts:
            artifact 0:
                path: C:\Users\itzg\git\prune-branches\build\distributions\prune-branches-1.2.4-SNAPSHOT.zip
        tags:
            cli
```

### Actual Behaviour

Only one artifact is listed and it is always the second one. To further confirm, when releasing with [this configuration](https://github.com/itzg/prune-branches/blob/e44185b8e1cb8648fd18cab13d0f66a5c55f877f/build.gradle#L46-L57) only the zip archive is published to [the release](https://github.com/itzg/prune-branches/releases/tag/v1.2.4). Prior to #515 both the zip and tgz would get published.

### Environment Information

- **Operating System**: Windows
- **JReleaser Version:** 0.9.0
- **JDK Version:** 17

Stack trace is not applicable.
