### ISSUE TITLE
[core] Add an option for platform replacements

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#578]
There are times when the platform of an artifact mist follow a different convention than the ones laid out by the os-maven-plugin, for example `amd64` instead of `x86_64`, or `aarch64` instead of `aarch_64`.

This feature should allow setting platform replacements at the project level, and at the assembler, distribution levels. Assemblers and distributions have priority and override project settings, such that

```yaml
# global
platform:
  replacements:
    aarch_64: aarch64

assemble:
  jlink:
    app:
      platform:
        replacements:
          osx-x86_64: mac
```

Results in the following model for the `app` assembler

```yaml
assemble:
  enabled: true
  jlink:
    app:
      enabled: true
      exported: true
      active: always
      platform:
        replacements:
          osx-x86_64: mac
          aarch_64: aarch64
```

**NOTE:** Platform replacements are only applicable to filenames and **not** to values of a `platform` property as found in `Artifact`, `Glob`, `FileSet`.
