### ISSUE TITLE
[upload] Support multiple repository targets in Artifactory

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#585]
Artifactory offers multiple types of repositories which may require different upload/download URLs depending on the `fileType`. JReleaser currently supports a single upload/download URL.

Proposal:

```yaml
upload:
  artifactory:
    kordamp:
      active: always
      signatures: true
      host: 'https://host/artifactory'
      repositories:
        # handles all kind of files
        - path: 'binaries/{{projectName}}/{{projectVersion}}/{{artifactFileName}}'
        # handles only RPM artifacts
        - path: 'rpms/{{artifactName}}/{{artifactVersion}}/{{artifactArch}}/{{artifactFileName}}'
          fileTypes:
          -  RPM
```
