### ISSUE TITLE
[model] Add a properties field to Environment

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#64]
These properties should be added to the template evaluating context without any prefix. Example

```yml
environment:
  properties:
    # define
    sdkman: /Users/duke/.sdkman/candidates

# use
assemble:   
  jlinks:
    app:
      active: always
      jdk:
        path: {{sdkman}}/java/16.0.0-zulu
        platform: osx
```
