### ISSUE TITLE
skipTag doesn't work when release is done

### ISSUE THREAD

**Issue by yschimke** [jreleaser/jreleaser#641]
### Task List

- [ ] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem (link to git repository is ideal)
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

1. Set skipTag in gradle configuration (https://github.com/yschimke/emulator-tools/blob/main/build.gradle.kts#L195)
2. git tag 0.4.5 & push
3. observe release process in github and new tag

### Expected Behaviour

Only tags created are by the manual push that triggers my release

### Actual Behaviour

Tag is still created with v0.4.5.0, 

https://github.com/yschimke/emulator-tools/releases/tag/v0.4.5.0

Please paste stacktraces from `[out|build|target]/jreleaser/trace.log`.

[trace.log](https://github.com/jreleaser/jreleaser/files/7790774/trace.log)

**Comment by yschimke** [comment]
This is probably a false report, but I can't work out what is creating the additional tag?

```
[DEBUG] resolving commits
[DEBUG] looking for tag that matches 'v0.4.5.0'
[DEBUG] looking for tags that match 'v.*', excluding 'v0.4.5.0'
[DEBUG] found tag v0.4.3.0
[DEBUG] sorting commits DESC
[INFO]  Generating changelog: build/jreleaser/release/CHANGELOG.md
[DEBUG] ## Changelog

307a227 Publishing path
487bd90 Publishing path
[INFO]  Calculating checksums
[DEBUG]   [checksum] checksum does not exist: build/jreleaser/checksums/emulator-tools/emulator-tools-0.4.5.0-osx-x86_64.zip.sha256
[INFO]    [checksum] build/jreleaser/assemble/emulator-tools/native-image/emulator-tools-0.4.5.0-osx-x86_64.zip.sha256
[DEBUG]   [checksum] reading build/jreleaser/checksums/emulator-tools/emulator-tools-0.4.5.0-osx-x86_64.zip.sha256
[INFO]  Signing files
[INFO]  Signing is not enabled. Skipping
[INFO]  Uploading is not enabled. Skipping
[INFO]  Releasing to https://github.com/yschimke/emulator-tools
[DEBUG] looking up release with tag v0.4.5.0 at repository yschimke/emulator-tools
[DEBUG] fetching release on yschimke/emulator-tools with tag v0.4.5.0
[DEBUG] release v0.4.5.0 does not exist
```

Any ideas?

**Comment by yschimke** [comment]
It definitely seems timed with the stages of jreleaser actions rather than then manual tag and push.

**Comment by aalmiray** [comment]
The project version is set to `0.4.5.0` while the tag was set to `0.4.5`? If so you have a difference with the actual tag (`0.4.5`) and the expected tag (`v0.4.5.0`). By default JReleaser expects the `tagName` to be `v{{projectVersion}}`. You did not specify a different pattern. 

If you desire the tag to follow `major.minor.build` then set `release.github.tagName` to `{{projectVersionMajor}}.{{projectVersionMinor}}.{{projectVersionPatch}}`. Data found in trace.log:

```
project:
    name: emulator-tools
    version: 0.4.5.0
    versionPattern: semver
    snapshot:
        enabled: false
        pattern: .*-SNAPSHOT
        label: early-access
        fullChangelog: false
    description: Android Emulator Tools
    longDescription: Android Emulator Tools
    website: https://github.com/yschimke/emulator-tools
    docsUrl: https://github.com/yschimke/emulator-tools
    license: Apache-2.0
    licenseUrl: https://github.com/yschimke/emulator-tools/blob/main/LICENSE
    copyright: Yuri Schimke
    authors:
        yschimke
    extraProperties:
        projectVersionMajor: 0
        projectVersionMinor: 4
        projectVersionPatch: 5
        projectVersionNumber: 0.4.5
        projectVersionTag: 0
        projectVersionWithUnderscores: 0_4_5_0
        projectVersionWithDashes: 0-4-5-0
        projectVersionNumberWithUnderscores: 0_4_5
        projectVersionNumberWithDashes: 0-4-5
        projectEffectiveVersionWithUnderscores: 0_4_5_0
        projectEffectiveVersionWithDashes: 0-4-5-0

...

release:
    github:
        enabled: true
        host: github.com
        owner: yschimke
        name: emulator-tools
        username: yschimke
        token: ************
        artifacts: true
        files: true
        checksums: true
        signatures: true
        repoUrl: https://{{repoHost}}/{{repoOwner}}/{{repoName}}
        repoCloneUrl: https://{{repoHost}}/{{repoOwner}}/{{repoName}}.git
        commitUrl: https://{{repoHost}}/{{repoOwner}}/{{repoName}}/commits
        srcUrl: https://{{repoHost}}/{{repoOwner}}/{{repoName}}/blob/{{repoBranch}}
        downloadUrl: https://{{repoHost}}/{{repoOwner}}/{{repoName}}/releases/download/{{tagName}}/{{artifactFile}}
        releaseNotesUrl: https://{{repoHost}}/{{repoOwner}}/{{repoName}}/releases/tag/{{tagName}}
        latestReleaseUrl: https://{{repoHost}}/{{repoOwner}}/{{repoName}}/releases/latest
        issueTrackerUrl: https://{{repoHost}}/{{repoOwner}}/{{repoName}}/issues
        tagName: v{{projectVersion}}
        releaseName: Release {{tagName}}
        branch: main
        commitAuthor:
            name: jreleaserbot
            email: jreleaser@kordamp.org
        sign: false
        skipTag: true
```
