### ISSUE TITLE
Gradle config: `changelog { enabled.set(false) }` is ignored?

### ISSUE THREAD

**Issue by bitspittle** [jreleaser/jreleaser#698]
In my Gradle config, I tried to explicitly disable changelog generation (I want to enable features incrementally).

```
release {
    github {
        changelog {
            enabled.set(false)
        }
    }
}
```

But when I run the `jreleaserConfig` task, I'm getting:

```
changelog:
    enabled: true
    links: false
    sort: DESC
    formatted: never
    hide:
        uncategorized: false
    contributors:
```

I tried changing some other values and they *did* get updated - just `enabled` seemed to get ignored.

---

**Note:** This also seems to affect `prerelease` too:

```
    prerelease {
        enabled.set(false)
    }
```

results in:

```
prerelease:
    enabled: true
```
