### ISSUE TITLE
[core] Linux/macOs launcher scripts may have a file extension

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#702]
For now the assumption is that linux/macOs launcher scripts do not use any file extension while windows executables/scripts must configure one (defaulting to `bat`).

However developers may choose to use an extension for linux/macOs launchers as it is the case for SchemaCrawler. 

Add an option to support this case, such as:

```yaml
distributions:
  app:
    executable: foo
    extension:
      unix: sh
      windows: cmd
```

This results in the following named templates

- distributionExecutable: foo

On linux/macOs
- distributionExecutableExtension: sh
- distributionFullExecutable: foo.sh

On windows
- distributionExecutableExtension: cmd
- distributionFullExecutable: foo.cmd

Where `extension.unix` defaults to empty, `extension.windows` defaults to `bat`. Deprecate existing `distributionExecutable` in favor of the `extension` section. 

cc: @sualeh

**Comment by aalmiray** [comment]
Thinking that perhaps the block should encompass the executable name and become:

```yaml
distributions:
  app:
    executable:
      name: foo
      unixExtension: sh
      windowsExtension: cmd
```
