### ISSUE TITLE
[assemblers] archive does not include file found at basedir

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#719]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem (link to git repository is ideal)
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. configure an `archive` assembler as
```
assemble:
  archive:
    jreleaser-archive:
      active: always
      attachPlatform: true
      formats: [ZIP, TAR, TAR_BZ2, TAR_GZ, TAR_XZ, TBZ2, TGZ, TXZ]
      fileSets:
        - input: '.'
          includes: [ 'VERSION' ]
```
2. Invoke `jreleaser assemble`

### Expected Behaviour

8 archives with the VERSION file inside.

### Actual Behaviour

8 empty archives

### Environment Information

- **Operating System**: N/A
- **JReleaser Version:** 1.0.0-M1
- **JDK Version:** N/A
