### ISSUE TITLE
[chocolatey] iconUrl not working?

### ISSUE THREAD

**Issue by gsmet** [jreleaser/jreleaser#734]
I have this section in my `jreleaser.yml`:
```
  chocolatey:
    active: ALWAYS
    continueOnError: true
    remoteBuild: true
    iconUrl: https://quarkus.io/assets/images/chocolatey-app-icon.png
```
so I would have expected an `iconUrl` in my nuspec file.

But somehow, it's missing in the commit:
https://github.com/quarkusio/chocolatey-bucket/commit/632f3c9a2a878882e46df7cf53695c9bdc0eecc2#diff-bc3540a4d7d6e309de9420c8ed5390779731a7264609b688f53931876f6216e7R26

I might be missing something obvious though but I couldn't find what the problem was after checking the documentation several times.
I see nothing related to that in `trace.log`.

**Comment by aalmiray** [comment]
Cannot reproduce with `v1.0.0-M1`

```
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated with JReleaser 1.0.0-M1 at 2022-02-02T17:29:13.269719+01:00 -->
<!-- Do not remove this test for UTF-8: if “Ω” doesn’t appear as greek uppercase omega letter enclosed in quotation marks, you should use an editor that supports UTF-8, not this one. -->
<package xmlns="http://schemas.microsoft.com/packaging/2015/06/nuspec.xsd">
  <metadata>
    <!-- required -->
    <id>quarkus</id>
    <version>2.7.0.Final</version>
    <authors>Quarkus Community</authors>
    <description>Create projects, manage extensions and perform build and development tasks for Quarkus,
the Kubernetes Native Java stack tailored for OpenJDK HotSpot and GraalVM.
</description>
    <!-- optional -->
    <title>quarkus</title>
    <projectUrl>https://quarkus.io</projectUrl>
    <copyright>Quarkus contributors</copyright>
    <licenseUrl></licenseUrl>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <tags>cli quarkus java quarkus cli</tags>
    <summary>CLI for Quarkus</summary>
    <projectSourceUrl>https://github.com/quarkusio/quarkus</projectSourceUrl>
    <packageSourceUrl>https://github.com/quarkusio/chocolatey-bucket</packageSourceUrl>
    <docsUrl>https://quarkus.io</docsUrl>
    <bugTrackerUrl>https://github.com/quarkusio/quarkus/issues</bugTrackerUrl>
    <releaseNotes>https://github.com/quarkusio/quarkus/releases/tag/2.7.0.Final</releaseNotes>
    <iconUrl>https://quarkus.io/assets/images/chocolatey-app-icon.png</iconUrl>
  </metadata>
  <files>
    <file src="tools\**" target="tools" />
  </files>
</package>
```

However I see it happening with `v0.10.0`

```
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated with JReleaser 0.10.0 at 2022-02-02T17:29:47.092564+01:00 -->
<!-- Do not remove this test for UTF-8: if “Ω” doesn’t appear as greek uppercase omega letter enclosed in quotation marks, you should use an editor that supports UTF-8, not this one. -->
<package xmlns="http://schemas.microsoft.com/packaging/2015/06/nuspec.xsd">
  <metadata>
    <!-- required -->
    <id>quarkus</id>
    <version>2.7.0.Final</version>
    <authors>Quarkus Community</authors>
    <description>Create projects, manage extensions and perform build and development tasks for Quarkus,
the Kubernetes Native Java stack tailored for OpenJDK HotSpot and GraalVM.
</description>
    <!-- optional -->
    <title>quarkus</title>
    <projectUrl>https://quarkus.io</projectUrl>
    <copyright>Quarkus contributors</copyright>
    <licenseUrl></licenseUrl>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <tags>cli quarkus java quarkus cli</tags>
    <summary>CLI for Quarkus</summary>
    <projectSourceUrl>https://github.com/quarkusio/quarkus</projectSourceUrl>
    <packageSourceUrl>https://github.com/quarkusio/chocolatey-bucket</packageSourceUrl>
    <docsUrl>https://quarkus.io</docsUrl>
    <bugTrackerUrl>https://github.com/quarkusio/quarkus/issues</bugTrackerUrl>
    <releaseNotes>https://github.com/quarkusio/quarkus/releases/tag/2.7.0.Final</releaseNotes>
    
  </metadata>
  <files>
    <file src="tools\**" target="tools" />
  </files>
</package>
```

Please upgrade to latest. Be aware that `v1.0.0-M2` will break compatibility for the `update` and `executable` sections due to

https://github.com/jreleaser/jreleaser/issues/702
https://github.com/jreleaser/jreleaser/issues/339

Your configuration file should look like this once `v1.0.0-M2` is posted

```
release:
  github:
    owner: quarkusio
    name: quarkus
    tagName: "{{projectVersion}}"
    overwrite: false
    update: 
      enabled: tru
      sections: [ ASSETS ]
    skipTag: true
    changelog:
      enabled: false
    milestone:
      close: false

distributions:
  quarkus:
    type: JAVA_BINARY
    executable: 
      name: quarkus
      windowsExtension: bat
    tags:
      - quarkus
      - cli
    artifacts:
      - path: target/quarkus-cli-{{projectVersion}}.zip
      - path: target/quarkus-cli-{{projectVersion}}.tar.gz
```
