### ISSUE TITLE
Ease GitLab CI usage by providing a ready to use Docker image

### ISSUE THREAD

**Issue by aepfli** [jreleaser/jreleaser#79]
Currently the steps to use jreleaser without maven or gradle on GitLab CI are tedious, and do need a lot of additional steps.

Instead of fetching and downloading jreleaser manually, it could be already prepackaged into a ready to use docker image.
As GitLab docker executor is always checking out the project to a structure which somehow reflects the project path, the current limitations of the docker image, with `/workspace` is limiting. 

Furthermore if somebody outside of the javaworld would want to use the jreleaser they most likely only want to have an easy way of just calling `jreleaser full-release` instead of `java -jar jreleaser-cli.jar full-release`.

eg the new snippet for GitLab CI would look like
```yaml
# Create a release
release:
  # using the new image
  image: jreleaser/jreleaser-slim:<version>
  # Bind to `deploy` stage
  stage: deploy
  # Set environment variables accordingly
  variables:
    JRELEASER_GPG_PASSPHRASE: $GPG_PASSPHRASE
    JRELEASER_GPG_PUBLIC_KEY: $GPG_PUBLIC_KEY
    JRELEASER_GPG_SECRET_KEY: $GPG_SECRET_KEY
    JRELEASER_GITLAB_TOKEN: $GL_PAT
    # Disable shallow cloning so that JReleaser can diff between tags
    # to generate a changelog
    GIT_DEPTH: 0
  #  Execute JReleaser
  script:
    - jreleaser full-release
```

This could be beneficiary in keeping a clean and simple build and reduce the needed boilerplate for the execution of jreleaser.
