### ISSUE TITLE
[core] Add support for universal binaries

### ISSUE THREAD

**Issue by helpermethod** [jreleaser/jreleaser#794]
**Is your feature request related to a problem? Please describe.**
The only way to distribute a platform-independent artifact with JReleaser is currently by using a distribution of type BINARY. This works fine as long as no packager is used, which then requires the use of a platform, which makes the configuration a little bit confusing (why use a platform in case of a platform-independent artifact?).

**Describe the solution you'd like**
It would be nice if JReleaser would provide some sort of UNIVERSAL distribution type, which describes a platform-independent distribution. 

For such a distribution, packagers would no longer require a platform.

**Describe alternatives you've considered**
I've used the BINARY distribution type and set the platform to `osx-x86_64` so that the Homebrew packager no longer complains.

**Additional context**
https://github.com/sdkman/sdkman-cli/pull/1070

**Comment by aalmiray** [comment]
I think the current restriction should stay in place however perhaps it could be bypassed by setting an extra property such as

```yaml
distributions:
  app:
    type: BINARY
    artifacts:
      - path: target/distributions/{{distributionName}}/{{distributionName}}-{{projectVersion}}.zip
        extraProperties:
            universal: true
```

WDYT @helpermethod ?
