### ISSUE TITLE
[chocolatey] Push workflow is run twice: once for main branch and a second time for the tag

### ISSUE THREAD

**Issue by gsmet** [jreleaser/jreleaser#819]
The Chocolatey push workflow seems to run twice:
- the first time for the push to the main branch
- the second time for the push to the tag

You can see this behavior in the Quarkus Chocolatey bucket: https://github.com/quarkusio/chocolatey-bucket/actions/workflows/push.yml .

I guess we would need something like:
```yaml
on:
  push:
    tags:
    branches-ignore:
    - '**'
```
in the workflow file.
