### ISSUE TITLE
[core] Support pre/post execution hooks

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#820]
Allow pre/post hooks for each execution step. There may be 2 types of hooks:

1. external script or executable with args. Arguments should include:
 - event type. BEFORE or AFTER.
 - event name. matches the given step such as changelog, release, etc. 
 - known values such as project name, project version, resolved tagname, basedir, and outputdir. 

2. A Java implementation of a given hook interface. Implementors will be located using the `ServiceLoader` interface. Callback methods should accept and event object (type, name), a read-only view of the evaluated model, basedir, and outputdir. 

Loading Java hooks requires configuring the location where required JARs are placed. This location should be set in the model config file or DSL.

**Comment by aalmiray** [comment]
A tentative option:

```
hooks:
  command:
    before:
      - filter:
          include: [checksum, sign]
          exclude: [release]
        cmd: 'echo {{ event.name }} {{ event.type }} {{ projectVersion }}'
    after:
      - cmd: 'echo {{ event.name }} DONE'
```

I know include/exclude as stated right there makes no sense, it’s to show possible config

This setup would allow running OS commands before and after specific steps. In the case of `after` it will be invoked after every single step. In the case of `before` it will be invoked based on filters applied to the event’s name

There will be a second type of hook that will let you load a Java class, taking the event and the context as inputs. This requires setting up an isolated classpath.

Questions:
1. Should command/script hooks be separate from Java hooks? for example, command hooks are actually "execution hooks" while Java hooks are "execution listeners". The distinction is that hooks receive explicit arguments as defined by consumers in the DSL while listeners receive the resolved model. Listeners **can** only be Java based.
2. Should execution failures still trigger hooks/listeners? If so, event types should be `BEFORE`, `AFTER`, `FAILURE`.
