### ISSUE TITLE
Cosign verify not working

### ISSUE THREAD

**Issue by codepitbull** [jreleaser/jreleaser#835]
### Steps to Reproduce

Add the following configuration to **jreleaser.yml**

```
signing:
  active: ALWAYS
  enabled: true
  armored: true
  mode: cosign
  cosign:
    version: 1.8.0
    privateKeyFile: cosign.key
    publicKeyFile: cosign.pub
```

Under both Linux (inside a GitHub-action) and on MacOS X (x86) you will see that jreleaser is downloading cosign in the
correct version but fails to verify it.

The reason is that jreleaser validates the version against stdout while cosign is reporting its version via err-out.

This makes cosign currently unusable with jreleaser.

I have already prepared a fix and will provide a PR shortly :)

### Environment Information

- **Operating System**: Linux and OSX
- **JReleaser Version:** 1.0.0
- **JDK Version:** 11 and 17
