### ISSUE TITLE
[core] brew settings are ignored

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#838]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem (link to git repository is ideal)
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Configure `brew` and `scoop` packagers using 2 `packagers` sections, such as
```
packagers:
  brew:
    active: always

packagers:
  scoop:
    active: always
```
2. Print out configuration by invoking `jreleaser config`

### Expected Behaviour

Both Brew and Scoop configuration printed out

### Actual Behaviour

Only Scoop is printed out

### Environment Information

- **Operating System**: N/A
- **JReleaser Version:** 1.0.0
- **JDK Version:** N/A
