### ISSUE TITLE
[core] Add a list of links to project

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#884]
Each link should have these properties:

- `url`.
- `type`. One of [homepage, bugtracker, faq, help, donation, translate, contact, vcs-browser, contribute]

If no link with type `homepage` is found then `project.website` will be used if defined.
if no link with type `bugtracker` is found then `release.*.issueTrackerUrl` will be used instead.

Based on appstream metadata https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-url

**Comment by aalmiray** [comment]
This section will look like this

```yaml
  links:
    homepage: https://acme.com/app
    bugTracker: https://vcs.acme.com/app/issues
    vcsBrowser: https://vcs.acme.com/app
    faq: https://acme.com/app/faq
    help: https://acme.com/app/help
    donation: https://acme.com/app/donations
    translate: https://acme.com/app/tr
    contact: https://acme.com/app/contact
    contribute: https://acme.com/app/contribute
```
