### ISSUE TITLE
[changelog] Add formatting options

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#91]
Inspired by https://github.com/marketplace/actions/release-drafter

DSL could look like

```yaml
release:
  github:
    overwrite: true
    changelog:
      formatted: ALWAYS
      change: '- {{commitShortHash}} {{commitTitle}}'
      labelers:
        - label: 'issue'
          title: 'Fixes #'
        - label: 'task'
          title: '[chore]'
      categories:
        - title: '✅ Issues'
          labels:
            - 'issue'
        - title: '🧰 Tasks'
          labels:
            - 'task'
      replacers:
        - search: '\[chore\] '
          replace: ''
        - search: '\[announce\]'
          replace: '📣'
```
