### ISSUE TITLE
[announce] Add a generic HTTP announcer

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#921]
Inspired by https://github.com/jreleaser/jreleaser/discussions/912

Similarly as it's done for `webhooks`, there should be an `http` announcer that takes the following properties:

```yml
announce:
  http:
    confluence:  # custom name
      active:
      url:
      username:
      password:
      authorization: BASIC
      method:  POST
      connectionTimeout:
      readTimeout:
      headers:
        Accept: application/json
        Content-Type: application/json
      payload:
      payloadTemplate:
```

`payload` defines the content as is while `payloadTemplate` points to a file. Both accept name templates.

cc: @anyulled
