### ISSUE TITLE
[core] Distribution artifacts are not included when releasing

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#938]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem (link to git repository is ideal)
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a project with a distribution such as https://github.com/aalmiray/app/
2. Build the artifacts
3. Perform a release

### Expected Behaviour

A release with 2 binary assets

### Actual Behaviour

No binary assets are found because the distribution is marked as disabled

**trace.log**
```
 distributions:
     app:
         enabled: false
         active: never
         type: JAVA_BINARY
```

### Environment Information

- **Operating System**: N/A
- **JReleaser Version:** 1.3.0-SNAPSHOT
- **JDK Version:** N/A
