### ISSUE TITLE
[changelog] Changelog is generated even if an external file is specified

### ISSUE THREAD

**Issue by charphi** [jreleaser/jreleaser#965]
### Steps to Reproduce

1. Set an external changelog file in a GitHub release section

### Expected Behaviour

No changelog should be generated.
JReleaser should check that the external file exists during dry-run.

### Actual Behaviour

Changelog is generated.
JReleaser doesn't check that the external file exists during dry-run.

**Comment by aalmiray** [comment]
I can't replicate this error with JReleaser `1.2.0`.

1. git clone https://github.com/aalmiray/foobar.git
2. edit `jreleaser.yml` so that the release section looks like this
```yml
release:
  github:
    overwrite: true
    sign: true
    discussionCategoryName: Announcements
    changelog:
      external: CHANGELOG.md
      preset: conventional-commits
      formatted: ALWAYS
      format: '- {{commitShortHash}} {{commitTitle}}'
      contributors:
        format: '- {{contributorName}}{{#contributorUsernameAsLink}} ({{.}}){{/contributorUsernameAsLink}}'
```
3. Create a file named `CHANGELOG.md` at the root with
```md
## Changelog

 - Fixed stuff
```
4. Run `jreleaser changelog -g`
```
[INFO]  Project version set to 1.0.0
[INFO]  Release is not snapshot
[INFO]  Timestamp is 2022-09-24T14:57:11.769714-05:00
[INFO]  HEAD is at 4df324c
[INFO]  Platform is osx-x86_64
[INFO]  dry-run set to true
[INFO]  Reading changelog from CHANGELOG.md
[INFO]  Generating changelog: out/jreleaser/release/CHANGELOG.md
[DEBUG] ## Changelog

 - Fixed stuff


[INFO]  Calculating checksums
```
6. Run `jreleaser release --dry-run`.

The changelog at `out/jreleaser/release/CHANGELOG.md` matches the content of `CHANGELOG.md` at the root.
